export const NOTIFICATION_CONSTANTS = {
  MAX_NOTIFICATIONS: 50,
  SSE_MAX_RETRIES: 5,
  SSE_RETRY_BASE_DELAY_MS: 1_000,
  SSE_RETRY_MAX_DELAY_MS: 10_000,
  SSE_SUBSCRIBE_DELAY_MS: 100,
  SSE_MESSAGE_PREVIEW_LENGTH: 100,
} as const;
