"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { use } from "react";
import { toast } from "sonner";
import { ContentCreationWizard } from "@/components/content-creation/content-creation-wizard";
import { PageLayout } from "@/components/page-layout";
import { CanAccess } from "@/components/permissions/can-access";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { apiClient } from "@/lib/api-client";
import { log } from "@/lib/logger";
import { CONTENT_PERMISSIONS } from "@/lib/permissions";
import { workspaceRoutes } from "@/lib/routes";
import { useWorkspace } from "@/providers/workspace-provider";
import type { ContentCreationFormData } from "@/types/content-creation";

export default function WorkspaceContentCreatePage({
  params,
}: {
  params: Promise<{ workspaceSlug: string }>;
}) {
  const resolvedParams = use(params);
  const { workspaceSlug } = resolvedParams;
  const { workspace, workspaceId } = useWorkspace();
  const router = useRouter();
  const searchParams = useSearchParams();
  const topicId = searchParams.get("topicId");

  const handleSubmit = async (formData: ContentCreationFormData) => {
    try {
      // Generate placeholder SEO data if missing
      const primaryKeywords =
        formData.primaryKeywords && formData.primaryKeywords.length > 0
          ? formData.primaryKeywords
          : [formData.contentType || "content"]; // Fallback to content type

      const metaDescription =
        formData.primaryKeywords && formData.primaryKeywords.length > 0
          ? `${formData.contentType} about ${formData.primaryKeywords.slice(0, 3).join(", ")} for ${formData.audienceType?.[0] || "readers"}`
          : `${formData.contentType} content for ${formData.industry || "general"} industry`;

      // Validate required SEO fields before API call
      if (!primaryKeywords || primaryKeywords.length === 0) {
        log.error("Primary keywords validation failed", {
          primaryKeywords,
          formData,
        });
        toast.error(
          "Unable to generate content: Primary keywords are required. Please add at least one keyword.",
        );
        return;
      }

      if (!metaDescription || metaDescription.trim().length === 0) {
        log.error("Meta description validation failed", { metaDescription });
        toast.error(
          "Unable to generate content: Meta description is required.",
        );
        return;
      }

      // Map wizard form data to API request format
      // Note: workspace_id is NOT included in body - it's passed as query param
      const createRequest = {
        topic_id: formData.topicId,
        title: `Content for Topic ${formData.topicId}`, // Will be generated by backend
        content_format: formData.format || "Markdown",
        status: "generating" as const,
        content_language: formData.language,
        metadata: {
          content_type: formData.contentType,
          target_platform: formData.platform,
          target_industry: formData.industry,
          target_audience: formData.audienceType,
          audience_size: formData.audienceSize,
          complexity_level: formData.readingLevel,
          content_tone: formData.tone,
          target_region: formData.region,
          content_objectives: formData.goals,
          content_word_count:
            formData.contentLength.type === "custom"
              ? formData.contentLength.custom?.value
              : undefined,
        },
        seo_data: {
          content_primary_keywords: primaryKeywords,
          content_search_intent: formData.searchIntent || [],
          content_meta_description: metaDescription.slice(0, 160), // Limit to 160 chars
        },
      };

      // Call backend API to create content
      const response = await apiClient.content.create(
        workspaceId,
        createRequest,
      );

      // Validate response has required ID field
      // Response structure: { content: {...}, operation_id: "...", message: "..." }
      if (!response?.content?.id) {
        log.error("Response missing content ID", { response });
        toast.error("Failed to get content ID from server response");
        return;
      }

      const contentId = response.content.id;

      toast.success(
        "Content generation started! Redirecting to progress page...",
      );

      // Navigate to content detail page to watch progress
      router.push(workspaceRoutes.contentDetail(workspaceSlug, contentId));
    } catch (error) {
      log.error("Failed to submit content creation", error);
      toast.error("Failed to start content generation. Please try again.");
      throw error;
    }
  };

  const handleCancel = () => {
    router.push(workspaceRoutes.content(workspaceSlug));
  };

  return (
    <PageLayout
      title="Create Content"
      description={`Create new content for ${workspace?.name || "workspace"}`}
    >
      <CanAccess
        permission={CONTENT_PERMISSIONS.CREATE}
        fallback={
          <Card className="border-destructive">
            <CardHeader>
              <CardTitle className="text-destructive">Access Denied</CardTitle>
              <CardDescription>
                You don't have permission to create content in this workspace.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Required permission:{" "}
                <code className="text-xs bg-muted px-1 rounded">
                  content.create
                </code>
              </p>
            </CardContent>
          </Card>
        }
      >
        <ContentCreationWizard
          initialTopicId={topicId || undefined}
          onSubmit={handleSubmit}
          onCancel={handleCancel}
        />
      </CanAccess>
    </PageLayout>
  );
}
