"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { use } from "react";
import { toast } from "sonner";
import { ContentCreationWizard } from "@/components/content-creation/content-creation-wizard";
import { PageLayout } from "@/components/page-layout";
import { apiClient } from "@/lib/api-client";
import { log } from "@/lib/logger";
import { workspaceRoutes } from "@/lib/routes";
import { useWorkspace } from "@/providers/workspace-provider";
import type { ContentCreationFormData } from "@/types/content-creation";

export default function WorkspaceContentCreatePage({
  params,
}: {
  params: Promise<{ workspaceSlug: string }>;
}) {
  const resolvedParams = use(params);
  const { workspaceSlug } = resolvedParams;
  const { workspace, workspaceId } = useWorkspace();
  const router = useRouter();
  const searchParams = useSearchParams();
  const topicId = searchParams.get("topicId");

  const breadcrumbs = [
    { label: "Workspaces", href: "/workspaces" },
    {
      label: workspace?.title || "...",
      href: workspaceRoutes.root(workspaceSlug),
    },
    { label: "Content", href: workspaceRoutes.content(workspaceSlug) },
    { label: "Create" },
  ];

  const handleSubmit = async (formData: ContentCreationFormData) => {
    try {
      log.info("Submitting content creation request", {
        workspaceId,
        formData,
      });

      // Map wizard form data to API request format
      const createRequest = {
        workspace_id: workspaceId,
        topic_id: formData.topicId,
        title: `Content for Topic ${formData.topicId}`, // Will be generated by backend
        content_format: formData.format || "Markdown",
        status: "generating" as const,
        content_language: formData.language,
        metadata: {
          content_type: formData.contentType,
          target_platform: formData.platform,
          target_industry: formData.industry,
          target_audience: formData.audienceType,
          audience_size: formData.audienceSize,
          complexity_level: formData.readingLevel,
          content_tone: formData.tone,
          target_region: formData.region,
          content_objectives: formData.goals,
          content_word_count:
            formData.contentLength.type === "custom"
              ? formData.contentLength.custom?.value
              : undefined,
        },
        seo_data: {
          content_primary_keywords: formData.primaryKeywords,
          content_search_intent: formData.searchIntent,
          content_meta_description: "", // Will be generated
        },
      };

      // Call backend API to create content
      const response = await apiClient.content.create(
        workspaceId,
        createRequest,
      );

      log.info("Content creation started successfully", response);
      toast.success(
        "Content generation started! You'll be notified when it's ready.",
      );

      // Navigate to content list or progress page
      router.push(workspaceRoutes.content(workspaceSlug));
    } catch (error) {
      log.error("Failed to submit content creation", error);
      toast.error("Failed to start content generation. Please try again.");
      throw error;
    }
  };

  const handleSaveDraft = async (
    formData: Partial<ContentCreationFormData>,
  ) => {
    log.info("Draft saved", { formData });
    // Draft is handled by the wizard's draft manager
  };

  const handleCancel = () => {
    router.push(workspaceRoutes.content(workspaceSlug));
  };

  return (
    <PageLayout
      title="Create Content"
      description={`Create new content for ${workspace?.title || "workspace"}`}
      breadcrumbs={breadcrumbs}
    >
      <ContentCreationWizard
        initialTopicId={topicId || undefined}
        onSubmit={handleSubmit}
        onSaveDraft={handleSaveDraft}
        onCancel={handleCancel}
      />
    </PageLayout>
  );
}
