/**
 * Centralized Schema Documentation and Validation
 *
 * This module provides comprehensive schema definitions, Zod validation schemas,
 * and field mappings for the Topic Builder data transformation layer.
 *
 * It serves as the single source of truth for understanding data structures
 * flowing between frontend components and backend APIs.
 */

import { z } from "zod";
import type { SaveTopicItem } from "./api";
import type { GeneratedTopic, TopicBuilderFormData } from "./topic-builder";

// ============================================================================
// VALIDATION SCHEMAS
// ============================================================================

/**
 * Zod validation schema for topic scores
 * Used in both frontend and backend topic structures
 */
export const TopicScoresSchema = z.object({
  /** Relevance score (0-100): How well the topic matches user criteria */
  relevance: z.number().min(0).max(100),
  /** Freshness score (0-100): How current/timely the topic is */
  freshness: z.number().min(0).max(100),
  /** Novelty score (0-100): How unique/original the topic approach is */
  novelty: z.number().min(0).max(100),
});

/**
 * Zod validation schema for frontend GeneratedTopic
 * Represents topics as generated by AI and displayed in the UI
 */
export const GeneratedTopicSchema = z.object({
  /** Unique topic identifier (frontend-generated) */
  id: z.string().min(1),
  /** Main topic headline/title */
  title: z.string().min(1).max(200),
  /** Specific angle or approach for the topic */
  angle: z.string().min(1).max(500),
  /** Brief topic description (optional in some flows) */
  description: z.string().optional(),
  /** AI-generated quality scores */
  scores: TopicScoresSchema,
  /** Channels/platforms this topic fits well */
  channel_fit: z.array(z.string()).default([]),
  /** Audience segments this topic appeals to */
  audience_fit: z.array(z.string()).default([]),
  /** Explanation of why this topic works well */
  why_it_works: z.string().min(1),
  /** Categorization tags for the topic */
  tags: z.array(z.string()).default([]),
  /** When the topic was generated (ISO string) */
  generated_at: z.string().datetime().optional(),
  /** Generation metadata */
  metadata: z
    .object({
      /** Original generation request parameters */
      generation_params: z.record(z.string(), z.unknown()).optional(),
      /** AI model used for generation */
      model_used: z.string().optional(),
      /** Generation confidence score */
      confidence: z.number().min(0).max(1).optional(),
    })
    .optional(),
});

/**
 * Zod validation schema for backend SaveTopicItem
 * Represents topics as expected by the save-topic API endpoint
 */
export const SaveTopicItemSchema = z.object({
  /** Topic title/headline (required for backend) */
  title: z.string().min(1).max(200),
  /** Specific angle or approach (required for backend) */
  angle: z.string().min(1).max(500),
  /** Channels/platforms this topic fits well (required for backend) */
  channel_fit: z.array(z.string()).min(1),
  /** Audience segments this topic appeals to (required for backend) */
  audience_fit: z.array(z.string()).min(1),
  /** AI-generated quality scores (required for backend) */
  scores: TopicScoresSchema,
  /** Explanation of why this topic works well (required for backend) */
  why_it_works: z.string().min(1),
  /** Categorization tags for the topic (required for backend) */
  tags: z.array(z.string()).min(1),
});

/**
 * Zod validation schema for TopicBuilderFormData
 * Represents the complete form state from the topic builder wizard
 */
export const TopicBuilderFormDataSchema = z.object({
  /** Wizard mode selection */
  wizardMode: z.enum(["quick", "comprehensive"]),
  /** Industry selection */
  industry: z.string().min(1),
  /** Custom industry specification (when industry = "Other") */
  industry_other: z.string().optional(),
  /** Industry-specific focus area */
  industry_specific_focus: z.string().optional(),
  /** Content type selection */
  content_type: z.string().min(1),
  /** Custom content type (when content_type = "Other") */
  content_type_other: z.string().optional(),
  /** Platform/channel selection */
  platform: z.string().optional(),
  /** Custom platform (when platform = "Other") */
  platform_other: z.string().optional(),
  /** Target audience description */
  audience: z.string().min(1),
  /** Reader expertise level */
  reader_level: z.string().min(1),
  /** Audience size estimate */
  audience_size: z.string().min(1),
  /** Demographic age groups */
  demographic_age: z.array(z.string()).default([]),
  /** Geographic/location demographics */
  demographic_location: z.array(z.string()).default([]),
  /** Content purpose/goals */
  purpose: z.array(z.string()).min(1),
  /** Custom purpose (when purpose includes "Other") */
  purpose_other: z.string().optional(),
  /** Content goals */
  content_goal: z.array(z.string()).default([]),
  /** Tone preferences */
  tone: z.array(z.string()).min(1),
  /** Custom tone (when tone includes "Other") */
  tone_other: z.string().optional(),
  /** Keywords to include/focus on */
  keywords: z.string().optional(),
  /** Additional notes from user */
  notes: z.string().optional(),
  /** Additional implementation notes */
  additional_notes: z.string().optional(),
  /** Number of topic ideas to generate */
  num_ideas: z.number().min(1).max(50).default(10),
  /** Regional preferences */
  region: z.string().optional(),
  /** Language preference */
  language: z.string().default("English"),
  /** Content timing preferences */
  content_timing_preference: z.string().optional(),
  /** Content originality preferences */
  content_originality_preference: z.string().optional(),
  /** Fresh vs evergreen content preference */
  fresh_vs_evergreen: z.string().optional(),
  /** Safe vs original content preference */
  safe_vs_original: z.string().optional(),
  /** Topics/themes to exclude */
  exclude: z.string().optional(),
  /** Specific focus areas */
  focus: z.string().optional(),
  /** Subject matter specifications */
  subject: z.string().optional(),
});

// ============================================================================
// FIELD MAPPING DOCUMENTATION
// ============================================================================

/**
 * Field mapping between GeneratedTopic (frontend) and SaveTopicItem (backend)
 *
 * This mapping defines how frontend topic data transforms to backend format
 * for the save-topic API endpoint.
 */
export const TOPIC_FIELD_MAPPING = {
  /** Direct field mappings (1:1) */
  direct: {
    title: "title",
    angle: "angle",
    scores: "scores",
    channel_fit: "channel_fit",
    audience_fit: "audience_fit",
    why_it_works: "why_it_works",
    tags: "tags",
  },
  /** Fields that exist only in frontend GeneratedTopic */
  frontendOnly: {
    id: "Unique identifier for frontend state management and UI operations",
    description: "Optional brief description used in some UI flows",
    generated_at: "Timestamp when topic was generated by AI",
    metadata: "Generation metadata including AI model info and confidence",
  },
  /** Fields that exist only in backend SaveTopicItem */
  backendOnly: {
    // Currently no backend-only fields, but this structure allows for future additions
  },
  /** Required transformations during frontend->backend conversion */
  transformations: {
    channel_fit: "Ensure array has at least one item before sending to backend",
    audience_fit:
      "Ensure array has at least one item before sending to backend",
    tags: "Ensure array has at least one item before sending to backend",
    remove_frontend_fields:
      "Remove id, description, generated_at, metadata fields",
  },
} as const;

/**
 * Field mapping between TopicBuilderFormData and backend API payload
 *
 * This mapping shows how form data transforms to the backend topic generation
 * request payload structure.
 */
export const FORM_TO_BACKEND_MAPPING = {
  /** Direct field mappings (1:1) */
  direct: [
    "wizardMode",
    "industry",
    "industry_other",
    "industry_specific_focus",
    "content_type",
    "content_type_other",
    "platform",
    "platform_other",
    "audience",
    "reader_level",
    "audience_size",
    "demographic_age",
    "demographic_location",
    "purpose",
    "purpose_other",
    "content_goal",
    "tone",
    "tone_other",
    "keywords",
    "notes",
    "additional_notes",
    "num_ideas",
    "region",
    "language",
    "content_timing_preference",
    "content_originality_preference",
    "fresh_vs_evergreen",
    "safe_vs_original",
    "exclude",
    "focus",
    "subject",
  ] as const,
  /** Fields added during transformation */
  added: {
    timestamp: "ISO timestamp added during API call preparation",
  },
} as const;

// ============================================================================
// TYPE GUARDS AND VALIDATION HELPERS
// ============================================================================

/**
 * Type guard to validate if an object is a valid GeneratedTopic
 */
export const isValidGeneratedTopic = (obj: unknown): obj is GeneratedTopic => {
  try {
    GeneratedTopicSchema.parse(obj);
    return true;
  } catch {
    return false;
  }
};

/**
 * Type guard to validate if an object is a valid SaveTopicItem
 */
export const isValidSaveTopicItem = (obj: unknown): obj is SaveTopicItem => {
  try {
    SaveTopicItemSchema.parse(obj);
    return true;
  } catch {
    return false;
  }
};

/**
 * Type guard to validate if an object is valid TopicBuilderFormData
 */
export const isValidTopicBuilderFormData = (
  obj: unknown,
): obj is TopicBuilderFormData => {
  try {
    TopicBuilderFormDataSchema.parse(obj);
    return true;
  } catch {
    return false;
  }
};

/**
 * Validates an array of topics for backend saving
 */
export const validateTopicsForSaving = (topics: unknown[]): SaveTopicItem[] => {
  return topics.map((topic, index) => {
    try {
      return SaveTopicItemSchema.parse(topic);
    } catch (error) {
      throw new Error(`Topic at index ${index} is invalid: ${error}`);
    }
  });
};

// ============================================================================
// TRANSFORMATION HELPERS
// ============================================================================

/**
 * Transforms a GeneratedTopic to SaveTopicItem format for backend API
 *
 * @param topic - Frontend GeneratedTopic object
 * @returns SaveTopicItem formatted for backend API
 * @throws Error if transformation fails due to missing required fields
 */
export const transformTopicForSaving = (
  topic: GeneratedTopic,
): SaveTopicItem => {
  // Validate input
  if (!isValidGeneratedTopic(topic)) {
    throw new Error("Invalid GeneratedTopic provided for transformation");
  }

  // Ensure required arrays have at least one item
  if (topic.channel_fit.length === 0) {
    throw new Error("channel_fit array cannot be empty for backend save");
  }
  if (topic.audience_fit.length === 0) {
    throw new Error("audience_fit array cannot be empty for backend save");
  }
  if (topic.tags.length === 0) {
    throw new Error("tags array cannot be empty for backend save");
  }

  // Transform to backend format (remove frontend-only fields)
  const backendTopic: SaveTopicItem = {
    title: topic.title,
    angle: topic.angle,
    channel_fit: topic.channel_fit,
    audience_fit: topic.audience_fit,
    scores: topic.scores,
    why_it_works: topic.why_it_works,
    tags: topic.tags,
  };

  // Validate output
  if (!isValidSaveTopicItem(backendTopic)) {
    throw new Error("Transformed topic failed backend validation");
  }

  return backendTopic;
};

/**
 * Transforms multiple GeneratedTopics to SaveTopicItems for bulk saving
 *
 * @param topics - Array of frontend GeneratedTopic objects
 * @returns Array of SaveTopicItem formatted for backend API
 */
export const transformTopicsForSaving = (
  topics: GeneratedTopic[],
): SaveTopicItem[] => {
  return topics.map((topic, index) => {
    try {
      return transformTopicForSaving(topic);
    } catch (error) {
      throw new Error(`Failed to transform topic at index ${index}: ${error}`);
    }
  });
};

/**
 * Adds required timestamp to TopicBuilderFormData for backend API
 *
 * @param formData - Frontend form data
 * @returns Form data with timestamp added
 */
export const prepareFormDataForBackend = (formData: TopicBuilderFormData) => {
  return {
    ...formData,
    timestamp: new Date().toISOString(),
  };
};

// ============================================================================
// VALIDATION ERROR HELPERS
// ============================================================================

/**
 * Extracts field-level validation errors from Zod validation result
 *
 * @param error - Zod validation error
 * @returns Object mapping field names to error messages
 */
export const extractValidationErrors = (
  error: z.ZodError,
): Record<string, string[]> => {
  const fieldErrors: Record<string, string[]> = {};

  error.issues.forEach((err) => {
    const fieldPath = err.path.join(".");
    if (!fieldErrors[fieldPath]) {
      fieldErrors[fieldPath] = [];
    }
    fieldErrors[fieldPath].push(err.message);
  });

  return fieldErrors;
};

/**
 * Creates user-friendly validation error messages
 *
 * @param fieldErrors - Field errors from extractValidationErrors
 * @returns Array of user-friendly error messages
 */
export const createUserFriendlyErrors = (
  fieldErrors: Record<string, string[]>,
): string[] => {
  return Object.entries(fieldErrors).map(([field, messages]) => {
    const fieldName = field
      .replace(/_/g, " ")
      .replace(/\b\w/g, (l) => l.toUpperCase());
    return `${fieldName}: ${messages.join(", ")}`;
  });
};

// ============================================================================
// EXPORTED TYPES FOR RUNTIME VALIDATION
// ============================================================================

export type ValidatedGeneratedTopic = z.infer<typeof GeneratedTopicSchema>;
export type ValidatedSaveTopicItem = z.infer<typeof SaveTopicItemSchema>;
export type ValidatedTopicBuilderFormData = z.infer<
  typeof TopicBuilderFormDataSchema
>;
export type ValidatedTopicScores = z.infer<typeof TopicScoresSchema>;
