/**
 * Centralized Schema Documentation and Validation
 *
 * This module provides comprehensive schema definitions, Zod validation schemas,
 * and field mappings for the Topic Builder data transformation layer.
 *
 * It serves as the single source of truth for understanding data structures
 * flowing between frontend components and backend APIs.
 */

import { z } from "zod";
import type { SaveTopicItem } from "./api";
import type { TopicData } from "./data-table";
import type { GeneratedTopic, TopicBuilderFormData } from "./topic-builder";

// ============================================================================
// VALIDATION SCHEMAS
// ============================================================================

/**
 * Zod validation schema for topic scores
 * Used in both frontend and backend topic structures
 */
export const TopicScoresSchema = z.object({
  /** Relevance score (0-100): How well the topic matches user criteria */
  relevance: z.number().min(0).max(100),
  /** Freshness score (0-100): How current/timely the topic is */
  freshness: z.number().min(0).max(100),
  /** Novelty score (0-100): How unique/original the topic approach is */
  novelty: z.number().min(0).max(100),
});

/**
 * Zod validation schema for frontend GeneratedTopic
 * Represents topics as generated by AI and displayed in the UI
 */
export const GeneratedTopicSchema = z.object({
  /** Unique topic identifier (frontend-generated) */
  id: z.string().min(1),
  /** Main topic headline/title */
  title: z.string().min(1).max(200),
  /** Specific angle or approach for the topic */
  angle: z.string().min(1).max(500),
  /** Brief topic description (optional in some flows) */
  description: z.string().optional(),
  /** AI-generated quality scores */
  scores: TopicScoresSchema,
  /** Channels/platforms this topic fits well */
  channel_fit: z.array(z.string()).default([]),
  /** Audience segments this topic appeals to */
  audience_fit: z.array(z.string()).default([]),
  /** Explanation of why this topic works well */
  why_it_works: z.string().min(1),
  /** Categorization tags for the topic */
  tags: z.array(z.string()).default([]),
  /** When the topic was generated (ISO string) */
  generated_at: z.string().datetime().optional(),
  /** Generation metadata */
  metadata: z
    .object({
      /** Original generation request parameters */
      generation_params: z.record(z.string(), z.unknown()).optional(),
      /** AI model used for generation */
      model_used: z.string().optional(),
      /** Generation confidence score */
      confidence: z.number().min(0).max(1).optional(),
    })
    .optional(),
});

/**
 * Zod validation schema for backend SaveTopicItem
 * Represents topics as expected by the save topics API endpoint
 */
export const SaveTopicItemSchema = z.object({
  /** Topic title/headline (required for backend) */
  title: z.string().min(1).max(200),
  /** Specific angle or approach (required for backend) */
  angle: z.string().min(1).max(500),
  /** Channels/platforms this topic fits well (required for backend) */
  channel_fit: z.array(z.string()).min(1),
  /** Audience segments this topic appeals to (required for backend) */
  audience_fit: z.array(z.string()).min(1),
  /** AI-generated quality scores (required for backend) */
  scores: TopicScoresSchema,
  /** Explanation of why this topic works well (required for backend) */
  why_it_works: z.string().min(1),
  /** Categorization tags for the topic (required for backend) */
  tags: z.array(z.string()).min(1),
});

/**
 * Zod validation schema for TopicData
 * Represents topics as displayed in the DataTable UI components
 * @see /docs/field-mapping-documentation.md for transformation rules from GeneratedTopic
 */
export const TopicDataSchema = z.object({
  /** Unique identifier for the topic */
  id: z.string().min(1),
  /** Main topic title/headline */
  name: z.string().min(1).max(200),
  /** Comprehensive description combining multiple topic fields */
  description: z.string().min(1),
  /** Category derived from tags or channel fit */
  category: z.string().min(1),
  /** Current status: generated, saving, saved, etc. */
  status: z.enum(["generated", "saving", "saved", "published", "archived"]),
  /** Priority level based on scoring algorithm */
  priority: z.enum(["low", "medium", "high"]),
  /** Source of the topic (always "AI Generated" for topic transformations) */
  source: z.string().min(1),
  /** Enhanced tags including channel and audience prefixes */
  tags: z.array(z.string()),
  /** ISO timestamp when topic was created */
  created: z.string().datetime(),
  /** ISO timestamp when topic was last modified */
  lastModified: z.string().datetime(),
  /** Assignee responsible for the topic */
  assignee: z.string().min(1),
  /** Estimated effort level based on novelty score */
  estimatedEffort: z.enum(["Low", "Medium", "High"]),
  /** Optional overall score (0-100) */
  score: z.number().min(0).max(100).optional(),
  /** Optional ranking position (e.g., "#1") */
  ranking: z.string().optional(),
  /** Optional formatted update date */
  updated: z.string().optional(),
  /** Optional author name */
  author: z.string().optional(),
  /** Optional inferred content type from channel fit */
  contentType: z.string().optional(),
});

/**
 * Zod validation schema for TopicBuilderFormData
 * Updated for TypeForm-style wizard flow with step-by-step validation
 */
export const TopicBuilderFormDataSchema = z.object({
  // Core wizard mode
  wizardMode: z.enum(["subject-first", "industry-first"]),

  // Industry selection
  industry: z.enum([
    "technology",
    "healthcare",
    "finance",
    "education",
    "travel",
    "food",
    "fashion",
    "business",
    "marketing",
    "science",
    "sports",
    "lifestyle",
    "government",
    "real-estate",
    "ecommerce",
    "hr",
    "legal",
    "fitness",
    "other",
  ]),
  industry_other: z.string().optional(),

  // Content type & platform (now optional - set in Flow)
  content_type: z
    .enum([
      "blog-post",
      "social-media",
      "video-content",
      "podcast",
      "infographic",
      "ebook-guide",
      "case-study",
      "whitepaper",
      "newsletter",
      "presentation",
      "press-release",
      "other",
    ])
    .optional(),
  platform: z
    .enum([
      "facebook",
      "instagram",
      "twitter",
      "linkedin",
      "tiktok",
      "youtube",
      "website",
      "blog",
      "vimeo",
      "other",
    ])
    .optional(),

  // Audience targeting
  audience: z.array(z.string()).optional(),

  // Content goals and style preferences
  purpose: z
    .array(
      z.enum([
        "educate-inform",
        "entertain-engage",
        "inspire-motivate",
        "persuade-convince",
        "promote-product",
        "drive-seo",
        "thought-leadership",
        "other",
      ]),
    )
    .min(1),
  purpose_other: z.string().optional(),
  tone: z
    .array(
      z.enum([
        "professional-formal",
        "casual-conversational",
        "friendly-warm",
        "humorous-playful",
        "serious-academic",
        "technical-analytical",
        "simple-accessible",
        "inspirational-uplifting",
        "other",
      ]),
    )
    .optional(),

  // Advanced options
  notes: z.string().optional(),
  num_topics: z.number().min(1).max(20).default(5),

  // Subject-first flow specific field
  subject: z.string().optional(),
});

/**
 * Step-specific validation schemas for TypeForm wizard flow
 * Each step has its own validation requirements for better UX
 *
 * Updated to reflect the new industry-first flow order.
 */

/**
 * Backend payload transformation schema - Updated for clean data structure
 */
export const backendTopicGenerationPayloadSchema = z.object({
  wizardMode: z.string(),
  industry: z.string(),
  industry_other: z.string().nullable().optional(),
  content_type: z.string().nullable().optional(),
  platform: z.string().nullable().optional(),
  audience: z.array(z.string()),
  purpose: z.array(z.string()),
  purpose_other: z.string().nullable().optional(),
  tone: z.array(z.string()).nullable().optional(),
  notes: z.string().nullable().optional(),
  num_topics: z.number(),
  subject: z.string().nullable().optional(),
  timestamp: z.string(),
});

// ============================================================================
// FIELD MAPPING DOCUMENTATION
// ============================================================================

/**
 * Field mapping between GeneratedTopic (frontend) and SaveTopicItem (backend)
 *
 * This mapping defines how frontend topic data transforms to backend format
 * for the topics/save API endpoint.
 */
export const TOPIC_FIELD_MAPPING = {
  /** Direct field mappings (1:1) */
  direct: {
    title: "title",
    angle: "angle",
    scores: "scores",
    channel_fit: "channel_fit",
    audience_fit: "audience_fit",
    why_it_works: "why_it_works",
    tags: "tags",
  },
  /** Fields that exist only in frontend GeneratedTopic */
  frontendOnly: {
    id: "Unique identifier for frontend state management and UI operations",
    description: "Optional brief description used in some UI flows",
    generated_at: "Timestamp when topic was generated by AI",
    metadata: "Generation metadata including AI model info and confidence",
  },
  /** Fields that exist only in backend SaveTopicItem */
  backendOnly: {
    // Currently no backend-only fields, but this structure allows for future additions
  },
  /** Required transformations during frontend->backend conversion */
  transformations: {
    channel_fit: "Ensure array has at least one item before sending to backend",
    audience_fit:
      "Ensure array has at least one item before sending to backend",
    tags: "Ensure array has at least one item before sending to backend",
    remove_frontend_fields:
      "Remove id, description, generated_at, metadata fields",
  },
} as const;

/**
 * Field mapping between TopicBuilderFormData and backend API payload
 *
 * This mapping shows how form data transforms to the backend topic generation
 * request payload structure.
 */
export const FORM_TO_BACKEND_MAPPING = {
  /** Direct field mappings (1:1) */
  direct: [
    "wizardMode",
    "industry",
    "industry_other",
    "content_type",
    "platform",
    "audience",
    "purpose",
    "purpose_other",
    "tone",
    "notes",
    "num_topics",
    "subject",
  ] as const,
  /** Fields added during transformation */
  added: {
    timestamp: "ISO timestamp added during API call preparation",
  },
} as const;

// ============================================================================
// TYPE GUARDS AND VALIDATION HELPERS
// ============================================================================

/**
 * Type guard to validate if an object is a valid GeneratedTopic
 */
export const isValidGeneratedTopic = (obj: unknown): obj is GeneratedTopic => {
  try {
    GeneratedTopicSchema.parse(obj);
    return true;
  } catch {
    return false;
  }
};

/**
 * Type guard to validate if an object is a valid SaveTopicItem
 */
export const isValidSaveTopicItem = (obj: unknown): obj is SaveTopicItem => {
  try {
    SaveTopicItemSchema.parse(obj);
    return true;
  } catch {
    return false;
  }
};

/**
 * Type guard to validate if an object is valid TopicBuilderFormData
 */
export const isValidTopicBuilderFormData = (
  obj: unknown,
): obj is TopicBuilderFormData => {
  try {
    TopicBuilderFormDataSchema.parse(obj);
    return true;
  } catch {
    return false;
  }
};

/**
 * Type guard to validate if an object is a valid TopicData
 */
export const isValidTopicData = (obj: unknown): obj is TopicData => {
  try {
    TopicDataSchema.parse(obj);
    return true;
  } catch {
    return false;
  }
};

/**
 * Validates an array of topics for backend saving
 */
export const validateTopicsForSaving = (topics: unknown[]): SaveTopicItem[] => {
  return topics.map((topic, index) => {
    try {
      return SaveTopicItemSchema.parse(topic);
    } catch (error) {
      throw new Error(`Topic at index ${index} is invalid: ${error}`);
    }
  });
};

/**
 * Validates an array of topics with detailed error reporting
 * @param topics Array of topics to validate
 * @returns Validation result with individual item success/error details
 */
export const validateArrayOfTopics = (
  topics: unknown[],
): {
  success: boolean;
  validTopics: SaveTopicItem[];
  errors: Array<{ index: number; error: string; topic: unknown }>;
} => {
  const validTopics: SaveTopicItem[] = [];
  const errors: Array<{ index: number; error: string; topic: unknown }> = [];

  topics.forEach((topic, index) => {
    const result = SaveTopicItemSchema.safeParse(topic);
    if (result.success) {
      validTopics.push(result.data);
    } else {
      const errorDetails = extractValidationErrors(result.error);
      const friendlyErrors = createUserFriendlyErrors(errorDetails);
      errors.push({
        index,
        error: friendlyErrors.join("; "),
        topic,
      });
    }
  });

  return {
    success: errors.length === 0,
    validTopics,
    errors,
  };
};

/**
 * Validates that all required fields are present in an object
 * @param data Object to validate
 * @param requiredFields Array of required field names
 * @returns Validation result with missing fields
 */
export const validateFieldPresence = (
  data: Record<string, unknown>,
  requiredFields: string[],
): {
  success: boolean;
  missingFields: string[];
  presentFields: string[];
} => {
  const missingFields: string[] = [];
  const presentFields: string[] = [];

  requiredFields.forEach((field) => {
    const value = data[field];
    if (value === undefined || value === null || value === "") {
      missingFields.push(field);
    } else if (Array.isArray(value) && value.length === 0) {
      missingFields.push(field);
    } else {
      presentFields.push(field);
    }
  });

  return {
    success: missingFields.length === 0,
    missingFields,
    presentFields,
  };
};

/**
 * Creates a detailed validation report for data transformation
 * @param data Data to validate
 * @param schema Zod schema to validate against
 * @param context Additional context for the validation
 * @returns Detailed validation report
 */
export const createValidationReport = <T>(
  data: unknown,
  schema: z.ZodSchema<T>,
  context?: string,
): {
  isValid: boolean;
  data?: T;
  errors: Array<{
    field: string;
    message: string;
    code: string;
    path: (string | number)[];
  }>;
  summary: string;
} => {
  const result = schema.safeParse(data);

  if (result.success) {
    return {
      isValid: true,
      data: result.data,
      errors: [],
      summary: `Validation successful${context ? ` for ${context}` : ""}`,
    };
  }

  const errors = result.error.issues.map((issue) => ({
    field: issue.path.join(".") || "root",
    message: issue.message,
    code: issue.code,
    path: issue.path.filter(
      (p): p is string | number =>
        typeof p === "string" || typeof p === "number",
    ),
  }));

  const summary = `Validation failed${context ? ` for ${context}` : ""}: ${errors.length} error(s) found`;

  return {
    isValid: false,
    errors,
    summary,
  };
};

// ============================================================================
// TRANSFORMATION HELPERS
// ============================================================================

/**
 * Transforms a GeneratedTopic to SaveTopicItem format for backend API
 *
 * This is a basic transformation utility. For enhanced error handling,
 * performance metrics, and batch processing, use the utilities in
 * @see /lib/transformation-utils.ts
 *
 * @param topic - Frontend GeneratedTopic object
 * @returns SaveTopicItem formatted for backend API
 * @throws Error if transformation fails due to missing required fields
 *
 * @example
 * ```typescript
 * // Basic transformation
 * const backendTopic = transformTopicForSaving(frontendTopic);
 *
 * // Enhanced transformation with error handling
 * import { transformTopicForSavingEnhanced } from '@/lib/transformation-utils';
 * const result = transformTopicForSavingEnhanced(frontendTopic);
 * if (result.success) {
 *   console.log('Transformed:', result.data);
 * } else {
 *   console.error('Error:', result.error.message);
 * }
 * ```
 */
export const transformTopicForSaving = (
  topic: GeneratedTopic,
): SaveTopicItem => {
  // Validate input
  if (!isValidGeneratedTopic(topic)) {
    throw new Error("Invalid GeneratedTopic provided for transformation");
  }

  // Ensure required arrays have at least one item
  if (topic.channel_fit.length === 0) {
    throw new Error("channel_fit array cannot be empty for backend save");
  }
  if (topic.audience_fit.length === 0) {
    throw new Error("audience_fit array cannot be empty for backend save");
  }
  if (topic.tags.length === 0) {
    throw new Error("tags array cannot be empty for backend save");
  }

  // Transform to backend format (remove frontend-only fields)
  const backendTopic: SaveTopicItem = {
    title: topic.title,
    angle: topic.angle,
    channel_fit: topic.channel_fit,
    audience_fit: topic.audience_fit,
    scores: topic.scores,
    why_it_works: topic.why_it_works,
    tags: topic.tags,
  };

  // Validate output
  if (!isValidSaveTopicItem(backendTopic)) {
    throw new Error("Transformed topic failed backend validation");
  }

  return backendTopic;
};

/**
 * Transforms multiple GeneratedTopics to SaveTopicItems for bulk saving
 *
 * This is a basic batch transformation utility. For enhanced error handling,
 * per-item error reporting, and performance optimization, use:
 * @see /lib/transformation-utils.ts - transformTopicsForSavingEnhanced()
 *
 * @param topics - Array of frontend GeneratedTopic objects
 * @returns Array of SaveTopicItem formatted for backend API
 * @throws Error if any topic transformation fails
 */
export const transformTopicsForSaving = (
  topics: GeneratedTopic[],
): SaveTopicItem[] => {
  return topics.map((topic, index) => {
    try {
      return transformTopicForSaving(topic);
    } catch (error) {
      throw new Error(`Failed to transform topic at index ${index}: ${error}`);
    }
  });
};

/**
 * Adds required timestamp to TopicBuilderFormData for backend API
 *
 * @param formData - Frontend form data
 * @returns Form data with timestamp added
 */
export const prepareFormDataForBackend = (formData: TopicBuilderFormData) => {
  return {
    ...formData,
    timestamp: new Date().toISOString(),
  };
};

// ============================================================================
// VALIDATION ERROR HELPERS
// ============================================================================

/**
 * Extracts field-level validation errors from Zod validation result
 *
 * @param error - Zod validation error
 * @returns Object mapping field names to error messages
 */
export const extractValidationErrors = (
  error: z.ZodError,
): Record<string, string[]> => {
  const fieldErrors: Record<string, string[]> = {};

  error.issues.forEach((err) => {
    const fieldPath = err.path.join(".") || "root";
    if (!fieldErrors[fieldPath]) {
      fieldErrors[fieldPath] = [];
    }
    fieldErrors[fieldPath].push(err.message);
  });

  return fieldErrors;
};

/**
 * Enhanced validation error extraction with detailed field information
 * @param error Zod validation error
 * @returns Enhanced field error information
 */
export const extractDetailedValidationErrors = (
  error: z.ZodError,
): Array<{
  field: string;
  message: string;
  code: string;
  path: (string | number)[];
  received?: unknown;
  expected?: string;
}> => {
  return error.issues.map((issue) => {
    const result: {
      field: string;
      message: string;
      code: string;
      path: (string | number)[];
      received?: unknown;
      expected?: string;
    } = {
      field: issue.path.join(".") || "root",
      message: issue.message,
      code: issue.code,
      path: issue.path.filter(
        (p): p is string | number =>
          typeof p === "string" || typeof p === "number",
      ),
    };

    // Add received value for certain error types
    if ("received" in issue) {
      result.received = issue.received;
    }

    // Add expected type information
    if (issue.code === "invalid_type") {
      result.expected =
        "expected" in issue ? String(issue.expected) : "unknown";
    }

    return result;
  });
};

/**
 * Creates user-friendly validation error messages
 *
 * @param fieldErrors - Field errors from extractValidationErrors
 * @returns Array of user-friendly error messages
 */
export const createUserFriendlyErrors = (
  fieldErrors: Record<string, string[]>,
): string[] => {
  return Object.entries(fieldErrors).map(([field, messages]) => {
    const fieldName = field
      .replace(/_/g, " ")
      .replace(/\b\w/g, (l) => l.toUpperCase());
    return `${fieldName}: ${messages.join(", ")}`;
  });
};

// ============================================================================
// EXPORTED TYPES FOR RUNTIME VALIDATION
// ============================================================================

export type ValidatedGeneratedTopic = z.infer<typeof GeneratedTopicSchema>;
export type ValidatedSaveTopicItem = z.infer<typeof SaveTopicItemSchema>;
export type ValidatedTopicBuilderFormData = z.infer<
  typeof TopicBuilderFormDataSchema
>;
export type ValidatedTopicScores = z.infer<typeof TopicScoresSchema>;
export type ValidatedTopicData = z.infer<typeof TopicDataSchema>;

// ============================================================================
// STEP-LEVEL VALIDATION SCHEMAS FOR REAL-TIME FEEDBACK
// ============================================================================

/**
 * Step-level validation schemas for React Hook Form integration
 * Allows real-time validation of individual wizard steps
 */
export const WizardModeStepSchema = TopicBuilderFormDataSchema.pick({
  wizardMode: true,
});

export const IndustryStepSchema = TopicBuilderFormDataSchema.pick({
  industry: true,
  industry_other: true,
});

export const SubjectStepSchema = TopicBuilderFormDataSchema.pick({
  subject: true,
});

export const AudienceStepSchema = TopicBuilderFormDataSchema.pick({
  audience: true,
});

export const PurposeStepSchema = TopicBuilderFormDataSchema.pick({
  purpose: true,
  purpose_other: true,
});

/**
 * Step schema mapping for dynamic validation
 * Maps wizard step IDs to their corresponding Zod schemas
 */
export const STEP_VALIDATION_SCHEMAS = {
  "wizard-mode": WizardModeStepSchema,
  industry: IndustryStepSchema,
  subject: SubjectStepSchema,
  audience: AudienceStepSchema,
  purpose: PurposeStepSchema,
} as const;

/**
 * Type for step validation schema keys
 */
export type StepValidationKey = keyof typeof STEP_VALIDATION_SCHEMAS;

// ============================================================================
// BACKEND RESPONSE VALIDATION SCHEMAS
// ============================================================================

/**
 * Backend API response validation schemas for runtime type safety
 */
export const BackendTopicGenerationResponseSchema = z.object({
  topics: z.array(GeneratedTopicSchema),
  request_id: z.string().optional(),
  model_used: z.string().optional(),
  generation_time_ms: z.number().optional(),
});

export const GetTopicsResponseSchema = z.object({
  topics: z.array(GeneratedTopicSchema),
  total_count: z.number().optional(),
  page: z.number().optional(),
  page_size: z.number().optional(),
});

export const SaveTopicResponseSchema = z.object({
  success: z.boolean(),
  saved_topics: z.array(z.string()).optional(),
  failed_topics: z.array(z.string()).optional(),
  message: z.string().optional(),
});

export type ValidatedBackendTopicGenerationResponse = z.infer<
  typeof BackendTopicGenerationResponseSchema
>;
export type ValidatedGetTopicsResponse = z.infer<
  typeof GetTopicsResponseSchema
>;
export type ValidatedSaveTopicResponse = z.infer<
  typeof SaveTopicResponseSchema
>;

// Enhanced validation result types
export interface ValidationResult<T> {
  success: boolean;
  data?: T;
  errors: string[];
  fieldErrors?: Record<string, string[]>;
  warnings?: string[];
}

export interface BatchValidationResult<T> {
  success: boolean;
  validItems: T[];
  invalidItems: Array<{
    index: number;
    item: unknown;
    errors: string[];
  }>;
  summary: {
    total: number;
    valid: number;
    invalid: number;
    successRate: number;
  };
}
