"use client";

import {
  Archive,
  Brain,
  CheckCircle,
  Clock,
  Copy,
  Edit2,
  Eye,
  FileText,
  Hash,
  Plus,
  RefreshCw,
  Search,
  Star,
  Tag,
  Trash2,
  XCircle,
  Zap,
} from "lucide-react";
import { PageLayout } from "@/components/page-layout";
import { DataTable } from "@/components/data-table";
import { Button } from "@/components/ui/button";

export default function MemoriesPage() {
  const breadcrumbs = [
    { label: "Configuration", href: "#" },
    { label: "Knowledge", href: "/knowledge" },
    { label: "Memories" },
  ];

  // Comprehensive memories data - AI context and learning
  const memoriesData = [
    {
      id: "1",
      title: "Brand Voice Guidelines for Tech Content",
      category: "Brand Guidelines",
      type: "Style Memory",
      status: "Approved",
      priority: "High",
      confidence: 95,
      approvalStatus: "Approved",
      approvedBy: "Sarah Johnson",
      approvedDate: "2024-01-15 10:30",
      usage: 247,
      lastUsed: "2024-01-22 15:30",
      expires: "Never",
      autoGenerated: true,
      sourceFlow: "AI Blog Post Generator",
      sourceContent: "Multiple blog posts analyzing tone and style",
      memoryContent:
        "The brand voice should be professional yet approachable, using technical terms sparingly and always explaining complex concepts. Avoid jargon like 'leverage', 'synergy', 'disrupt'. Prefer active voice and conversational tone. Use data-driven insights and practical examples.",
      tags: ["brand voice", "content style", "writing guidelines"],
      triggers: [
        "blog post generation",
        "social media content",
        "email campaigns",
      ],
      learningSource: "Analyzed 47 approved content pieces",
      createdBy: "AI Assistant",
      created: "2024-01-15 09:20",
      lastModified: "2024-01-22 14:15",
      contexts: ["Content Creation", "Social Media", "Email Marketing"],
    },
    {
      id: "2",
      title: "Customer Pain Points - E-commerce Platform",
      category: "Customer Insights",
      type: "Behavioral Memory",
      status: "Approved",
      priority: "High",
      confidence: 88,
      approvalStatus: "Approved",
      approvedBy: "Mike Chen",
      approvedDate: "2024-01-10 14:20",
      usage: 156,
      lastUsed: "2024-01-22 16:20",
      expires: "2024-07-15",
      autoGenerated: true,
      sourceFlow: "Customer Support Automation",
      sourceContent: "Analysis of 200+ support tickets",
      memoryContent:
        "Top customer pain points: 1) Difficulty finding product information (34% of tickets), 2) Shipping delays and tracking issues (28%), 3) Return/refund process confusion (19%), 4) Account login problems (12%), 5) Payment processing errors (7%). Customers respond best to empathetic acknowledgment and clear step-by-step solutions.",
      tags: [
        "customer support",
        "pain points",
        "e-commerce",
        "user experience",
      ],
      triggers: [
        "support response generation",
        "product descriptions",
        "FAQ content",
      ],
      learningSource: "Support ticket analysis from Dec 2023 - Jan 2024",
      createdBy: "AI Assistant",
      created: "2024-01-10 11:45",
      lastModified: "2024-01-20 16:30",
      contexts: ["Customer Service", "Product Marketing", "E-commerce"],
    },
    {
      id: "3",
      title: "LinkedIn Audience Engagement Patterns",
      category: "Social Media Insights",
      type: "Performance Memory",
      status: "Pending Review",
      priority: "Medium",
      confidence: 92,
      approvalStatus: "Pending",
      approvedBy: null,
      approvedDate: null,
      usage: 134,
      lastUsed: "2024-01-22 14:45",
      expires: "2024-06-22",
      autoGenerated: true,
      sourceFlow: "Social Media Content Pipeline",
      sourceContent: "Performance data from 85 LinkedIn posts",
      memoryContent:
        "Best performing LinkedIn content: Posts with 5-7 slides get 40% more engagement than single posts. Tuesday-Thursday 9-11 AM shows highest engagement. Questions in first slide increase comments by 60%. Include 2-3 relevant hashtags max. Avoid promotional language in first 2 slides. Behind-the-scenes and educational content performs 3x better than direct product promotion.",
      tags: ["linkedin", "social media", "engagement", "b2b marketing"],
      triggers: ["linkedin carousel creation", "social media scheduling"],
      learningSource: "LinkedIn analytics from 85 posts over 3 months",
      createdBy: "AI Assistant",
      created: "2024-01-08 13:20",
      lastModified: "2024-01-22 10:15",
      contexts: ["Social Media", "B2B Marketing", "Content Strategy"],
    },
    {
      id: "4",
      title: "Email Newsletter Open Rate Optimization",
      category: "Email Marketing",
      type: "Performance Memory",
      status: "Rejected",
      priority: "High",
      confidence: 89,
      approvalStatus: "Rejected",
      approvedBy: "Alex Rivera",
      approvedDate: "2024-01-06 09:15",
      rejectionReason: "Data sample size too small for reliable insights",
      usage: 203,
      lastUsed: "2024-01-22 08:00",
      expires: "2024-08-01",
      autoGenerated: true,
      sourceFlow: "Newsletter Content Creator",
      sourceContent: "A/B test results from 24 newsletter campaigns",
      memoryContent:
        "Subject line optimization: Personal pronouns ('Your', 'You') increase opens by 23%. Numbers and urgency ('5 minutes', 'Today only') boost opens 18%. Avoid spam triggers like 'Free', 'Buy now', '!!!'. Optimal length: 30-50 characters. Tuesday sends get highest opens (24.5%), Friday lowest (16.2%). Preview text should complement, not repeat subject line.",
      tags: ["email marketing", "subject lines", "open rates", "a/b testing"],
      triggers: ["newsletter creation", "email campaign setup"],
      learningSource: "24 A/B tests across 12,450 subscribers",
      createdBy: "AI Assistant",
      created: "2024-01-05 07:30",
      lastModified: "2024-01-21 08:45",
      contexts: ["Email Marketing", "Newsletter", "Campaign Optimization"],
    },
    {
      id: "5",
      title: "Product Description Conversion Factors",
      category: "E-commerce Optimization",
      type: "Conversion Memory",
      status: "Approved",
      priority: "High",
      confidence: 94,
      approvalStatus: "Approved",
      approvedBy: "Emma Davis",
      approvedDate: "2023-12-21 08:45",
      usage: 89,
      lastUsed: "2024-01-22 16:20",
      expires: "Never",
      autoGenerated: true,
      sourceFlow: "Product Description Generator",
      sourceContent: "Conversion analysis from 150+ product pages",
      memoryContent:
        "High-converting product descriptions include: Benefit-focused headlines (not feature-focused), Social proof within first 100 words, Specific numbers vs vague claims ('Saves 2 hours daily' vs 'Saves time'), Address 3 main objections early, Use power words: 'Proven', 'Guaranteed', 'Exclusive', Bullets for features, paragraphs for benefits. Mobile-optimized: shorter paragraphs, larger fonts.",
      tags: [
        "product descriptions",
        "e-commerce",
        "conversion optimization",
        "sales copy",
      ],
      triggers: ["product description generation", "sales page creation"],
      learningSource: "Conversion rate analysis from 150 product pages",
      createdBy: "AI Assistant",
      created: "2023-12-20 14:30",
      lastModified: "2024-01-18 11:20",
      contexts: ["E-commerce", "Product Marketing", "Sales"],
    },
    {
      id: "6",
      title: "Video Content Engagement Insights",
      category: "Video Marketing",
      type: "Performance Memory",
      status: "Pending Review",
      priority: "Medium",
      confidence: 86,
      approvalStatus: "Pending",
      approvedBy: null,
      approvedDate: null,
      usage: 45,
      lastUsed: "2024-01-20 14:15",
      expires: "2024-09-15",
      autoGenerated: true,
      sourceFlow: "YouTube Script Writer",
      sourceContent: "Performance data from 23 educational videos",
      memoryContent:
        "YouTube optimization patterns: Hook within first 15 seconds crucial (60% viewer drop-off point). Educational content needs clear structure: Problem → Solution → Steps → Results. Optimal video length 8-12 minutes for tutorials. Include pattern interrupt every 90 seconds. End screens boost channel subscriptions by 300%. Thumbnails with faces get 35% more clicks than text-only.",
      tags: ["youtube", "video marketing", "engagement", "educational content"],
      triggers: ["video script creation", "youtube optimization"],
      learningSource: "Analytics from 23 videos, 450K total views",
      createdBy: "AI Assistant",
      created: "2024-01-12 16:45",
      lastModified: "2024-01-20 14:15",
      contexts: ["Video Content", "YouTube", "Educational Marketing"],
    },
    {
      id: "7",
      title: "Customer Support Response Effectiveness",
      category: "Customer Service",
      type: "Response Memory",
      status: "Approved",
      priority: "High",
      confidence: 91,
      approvalStatus: "Approved",
      approvedBy: "Jennifer Taylor",
      approvedDate: "2023-12-01 11:30",
      usage: 312,
      lastUsed: "2024-01-22 16:45",
      expires: "2024-12-31",
      autoGenerated: true,
      sourceFlow: "Customer Support Automation",
      sourceContent: "Customer satisfaction scores from 500+ tickets",
      memoryContent:
        "Effective support responses follow HEART model: Hear (acknowledge specific issue), Empathize (show understanding), Apologize (when appropriate), Respond (clear solution), Thank (appreciate patience). Response time under 4 hours = 92% satisfaction. Over 24 hours = 34% satisfaction. Customers prefer step-by-step solutions over links to documentation. Follow-up questions reduce re-contact by 45%.",
      tags: [
        "customer support",
        "response quality",
        "satisfaction",
        "resolution",
      ],
      triggers: ["support ticket responses", "customer communication"],
      learningSource: "500+ support interactions with satisfaction tracking",
      createdBy: "AI Assistant",
      created: "2023-11-30 10:15",
      lastModified: "2024-01-19 13:40",
      contexts: ["Customer Support", "Service Quality", "Communication"],
    },
    {
      id: "8",
      title: "Industry-Specific Terminology Preferences",
      category: "Industry Knowledge",
      type: "Vocabulary Memory",
      status: "Draft",
      priority: "Medium",
      confidence: 87,
      approvalStatus: "Draft",
      approvedBy: null,
      approvedDate: null,
      usage: 167,
      lastUsed: "2024-01-22 12:30",
      expires: "Never",
      autoGenerated: true,
      sourceFlow: "Multi-industry Content",
      sourceContent: "Terminology analysis across different sectors",
      memoryContent:
        "Industry language preferences: Tech: 'solution' > 'product', 'optimize' > 'improve', 'scalable' > 'big'. Healthcare: 'patient outcomes' > 'results', 'evidence-based' > 'proven'. Finance: 'portfolio' > 'collection', 'yield' > 'return', 'leverage' acceptable. Education: 'learning outcomes' > 'results', 'methodology' > 'method'. Avoid corporate buzzwords across all industries.",
      tags: [
        "industry terminology",
        "vocabulary",
        "sector-specific",
        "language",
      ],
      triggers: ["industry-specific content", "professional writing"],
      learningSource: "Content analysis across 8 industry verticals",
      createdBy: "AI Assistant",
      created: "2024-01-03 11:25",
      lastModified: "2024-01-22 12:30",
      contexts: [
        "Professional Writing",
        "Industry Content",
        "B2B Communication",
      ],
    },
    {
      id: "9",
      title: "Seasonal Content Performance Patterns",
      category: "Content Strategy",
      type: "Temporal Memory",
      status: "Approved",
      priority: "Low",
      confidence: 83,
      approvalStatus: "Approved",
      approvedBy: "David Park",
      approvedDate: "2024-01-02 16:45",
      usage: 78,
      lastUsed: "2024-01-22 09:15",
      expires: "2025-01-15",
      autoGenerated: true,
      sourceFlow: "Seasonal Marketing Analysis",
      sourceContent: "12 months of content performance data",
      memoryContent:
        "Seasonal content insights: Q1 (Jan-Mar): 'New Year, New You' themes perform well, productivity content peaks. Q2 (Apr-Jun): Spring cleaning, optimization, fresh start content. Q3 (Jul-Sep): Back-to-school, preparation themes. Q4 (Oct-Dec): Year-end reviews, holiday themes, planning ahead. Avoid major launches in August and late December. Educational content performs consistently year-round.",
      tags: ["seasonal marketing", "content calendar", "timing", "performance"],
      triggers: ["content planning", "seasonal campaigns"],
      learningSource: "12 months content performance across all channels",
      createdBy: "AI Assistant",
      created: "2024-01-01 15:00",
      lastModified: "2024-01-15 09:30",
      contexts: ["Content Strategy", "Campaign Planning", "Marketing Calendar"],
    },
    {
      id: "10",
      title: "Competitor Analysis - Content Gaps",
      category: "Competitive Intelligence",
      type: "Market Memory",
      status: "Pending Review",
      priority: "Medium",
      confidence: 90,
      approvalStatus: "Pending",
      approvedBy: null,
      approvedDate: null,
      usage: 92,
      lastUsed: "2024-01-21 16:20",
      expires: "2024-04-21",
      autoGenerated: true,
      sourceFlow: "Competitive Content Analysis",
      sourceContent: "Analysis of 5 main competitors' content strategies",
      memoryContent:
        "Content gap opportunities: Competitors focus heavily on product features, missing emotional benefits. Lack of behind-the-scenes content (opportunity for authenticity). Under-serving mid-market segment with educational content. No competitors addressing 'implementation challenges' - high search volume, low competition. Video content gap in 'getting started' category. Case studies focus on large enterprises, missing SMB stories.",
      tags: [
        "competitive analysis",
        "content gaps",
        "market opportunities",
        "strategy",
      ],
      triggers: ["content strategy planning", "competitive positioning"],
      learningSource: "6-month analysis of 5 competitor content strategies",
      createdBy: "AI Assistant",
      created: "2024-01-18 14:20",
      lastModified: "2024-01-21 16:20",
      contexts: ["Competitive Strategy", "Content Planning", "Market Analysis"],
    },
  ];

  const columns = [
    { key: "title", header: "Memory Title", width: "280px" },
    { key: "category", header: "Category", width: "160px" },
    { key: "type", header: "Type", width: "140px" },
    { key: "approvalStatus", header: "Approval Status", width: "130px" },
    { key: "confidence", header: "Confidence", width: "100px" },
    { key: "usage", header: "Usage", width: "80px" },
    { key: "approvedBy", header: "Approved By", width: "120px" },
    { key: "created", header: "Created", width: "120px" },
  ];

  const emptyActions = [
    {
      label: "Learn More",
      icon: <Brain className="h-4 w-4" />,
      href: "/docs/memories",
    },
  ];

  const tableActions = (
    <Button variant="outline">
      <RefreshCw className="h-4 w-4 mr-2" />
      Refresh Memories
    </Button>
  );

  // Row click handler
  const handleRowClick = (row: Record<string, any>) => {
    console.log("Viewing memory:", row.title);
    // In a real app, you'd navigate to `/memories/${row.id}`
  };

  // Custom row actions specific to memories
  const rowActions = [
    {
      label: "View Memory",
      icon: <Eye className="h-4 w-4" />,
      onClick: (row: Record<string, any>) =>
        console.log("View memory:", row.title),
    },
    {
      label: "Approve Memory",
      icon: <CheckCircle className="h-4 w-4" />,
      onClick: (row: Record<string, any>) =>
        console.log("Approve memory:", row.title),
    },
    {
      label: "Reject Memory",
      icon: <XCircle className="h-4 w-4" />,
      onClick: (row: Record<string, any>) =>
        console.log("Reject memory:", row.title),
      variant: "destructive" as const,
    },
    {
      label: "Edit Memory",
      icon: <Edit2 className="h-4 w-4" />,
      onClick: (row: Record<string, any>) =>
        console.log("Edit memory:", row.title),
    },
    {
      label: "Duplicate Memory",
      icon: <Copy className="h-4 w-4" />,
      onClick: (row: Record<string, any>) =>
        console.log("Duplicate memory:", row.title),
    },
    {
      label: "Add to Favorites",
      icon: <Star className="h-4 w-4" />,
      onClick: (row: Record<string, any>) =>
        console.log("Favorite memory:", row.title),
    },
    {
      label: "View Source",
      icon: <Search className="h-4 w-4" />,
      onClick: (row: Record<string, any>) =>
        console.log("View source:", row.title),
    },
    {
      label: "Delete Memory",
      icon: <Trash2 className="h-4 w-4" />,
      onClick: (row: Record<string, any>) =>
        console.log("Delete memory:", row.title),
      variant: "destructive" as const,
    },
  ];

  return (
    <PageLayout
      title="Memories"
      description="View and manage auto-generated memories from your flow executions and AI interactions. Approve or reject memories to control AI learning."
      breadcrumbs={breadcrumbs}
    >
      <DataTable
        columns={columns}
        data={memoriesData}
        emptyTitle="No memories generated yet"
        emptyDescription="Memories will be automatically generated and stored when you run flows that process information and create contextual insights."
        emptyActions={emptyActions}
        emptyIcon={<Archive className="h-8 w-8 text-muted-foreground" />}
        searchPlaceholder="Search memories by title, category, type, approval status..."
        actions={tableActions}
        onRowClick={handleRowClick}
        rowActions={rowActions}
        pageSize={10}
        searchFields={[
          "title",
          "category",
          "type",
          "approvalStatus",
          "tags",
          "contexts",
        ]}
      />
    </PageLayout>
  );
}
