"use client";

import {
  Calendar,
  CheckCircle,
  Clock,
  Copy,
  Edit2,
  Eye,
  ExternalLink,
  FileText,
  Hash,
  Image,
  MessageSquare,
  Play,
  Plus,
  Send,
  Share2,
  Trash2,
  Video,
  Zap,
} from "lucide-react";
import { PageLayout } from "@/components/page-layout";
import { DataTable } from "@/components/data-table";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export default function ContentPage() {
  const breadcrumbs = [{ label: "Library", href: "#" }, { label: "Content" }];

  // Comprehensive content data generated by flows
  const contentData = [
    {
      id: "1",
      title:
        "The Future of AI in Software Development: 10 Game-Changing Trends",
      type: "Blog Post",
      contentType: "article",
      status: "Published",
      publishedTo: "Company Blog",
      publishDate: "2024-01-22 09:00",
      scheduledDate: null,
      flowName: "AI Blog Post Generator",
      flowId: "1",
      wordCount: 1547,
      readTime: "6 min read",
      engagement: { views: 2847, likes: 156, shares: 42 },
      seoScore: 94,
      author: "AI Assistant",
      humanReviewer: "Sarah Johnson",
      keywords: [
        "artificial intelligence",
        "software development",
        "automation",
      ],
      platforms: ["WordPress", "Medium"],
      lastModified: "2024-01-22 08:45",
      created: "2024-01-22 08:30",
      content:
        "As we stand on the precipice of a technological revolution, artificial intelligence continues to reshape the landscape of software development...",
    },
    {
      id: "2",
      title: "5 LinkedIn Carousel: Productivity Hacks for Remote Teams",
      type: "LinkedIn Carousel",
      contentType: "carousel",
      status: "Scheduled",
      publishedTo: null,
      publishDate: null,
      scheduledDate: "2024-01-23 10:00",
      flowName: "Social Media Content Pipeline",
      flowId: "2",
      slideCount: 5,
      engagement: { impressions: 0, clicks: 0, comments: 0 },
      author: "AI Assistant",
      humanReviewer: "Mike Chen",
      keywords: ["remote work", "productivity", "team management"],
      platforms: ["LinkedIn"],
      lastModified: "2024-01-22 14:20",
      created: "2024-01-22 14:15",
      content:
        "Slide 1: 🏠 Remote Work Reality Check\nSlide 2: 📊 Time Tracking Tools That Actually Work\nSlide 3: 🤝 Communication Protocols...",
    },
    {
      id: "3",
      title: "Twitter Thread: Breaking Down AI Ethics - 15 Essential Points",
      type: "Twitter Thread",
      contentType: "thread",
      status: "Draft",
      publishedTo: null,
      publishDate: null,
      scheduledDate: null,
      flowName: "Social Media Content Pipeline",
      flowId: "2",
      tweetCount: 15,
      characterCount: 1890,
      engagement: { retweets: 0, likes: 0, replies: 0 },
      author: "AI Assistant",
      humanReviewer: "Alex Rivera",
      keywords: ["AI ethics", "technology", "responsibility"],
      platforms: ["Twitter"],
      lastModified: "2024-01-22 13:30",
      created: "2024-01-22 13:25",
      content:
        "🧵 Thread: Why AI Ethics Matter More Than Ever (1/15)\n\n1/ As AI becomes ubiquitous, we need frameworks for responsible development...",
    },
    {
      id: "4",
      title: "Weekly Tech Digest: January 15-21, 2024",
      type: "Newsletter",
      contentType: "email",
      status: "Published",
      publishedTo: "MailChimp Campaign",
      publishDate: "2024-01-21 08:00",
      scheduledDate: null,
      flowName: "Newsletter Content Creator",
      flowId: "3",
      wordCount: 892,
      recipientCount: 12450,
      engagement: { openRate: "24.5%", clickRate: "3.2%", unsubscribes: 18 },
      author: "AI Assistant",
      humanReviewer: "Jennifer Taylor",
      keywords: ["tech news", "startups", "innovation"],
      platforms: ["MailChimp", "Substack"],
      lastModified: "2024-01-21 07:45",
      created: "2024-01-21 07:00",
      content:
        "🚀 This Week in Tech\n\nHi there,\n\nAnother exciting week in the tech world! Here are the top stories that caught our attention...",
    },
    {
      id: "5",
      title: "Reddit Post: Ask r/programming - Best Practices for Code Reviews",
      type: "Reddit Post",
      contentType: "discussion",
      status: "Published",
      publishedTo: "r/programming",
      publishDate: "2024-01-22 16:30",
      scheduledDate: null,
      flowName: "Community Content Generator",
      flowId: "8",
      wordCount: 324,
      engagement: { upvotes: 87, comments: 23, awards: 2 },
      author: "AI Assistant",
      humanReviewer: "Carlos Mendez",
      keywords: ["code review", "best practices", "programming"],
      platforms: ["Reddit"],
      lastModified: "2024-01-22 16:25",
      created: "2024-01-22 16:20",
      content:
        "What are your go-to practices for effective code reviews?\n\nI've been leading a team for 6 months now, and I'm looking to improve our code review process...",
    },
    {
      id: "6",
      title:
        "YouTube Script: Machine Learning Fundamentals Explained in 10 Minutes",
      type: "Video Script",
      contentType: "script",
      status: "Approved",
      publishedTo: null,
      publishDate: null,
      scheduledDate: "2024-01-25 14:00",
      flowName: "YouTube Script Writer",
      flowId: "5",
      wordCount: 1823,
      estimatedDuration: "10:45",
      author: "AI Assistant",
      humanReviewer: "David Park",
      keywords: ["machine learning", "education", "tutorial"],
      platforms: ["YouTube"],
      lastModified: "2024-01-22 11:10",
      created: "2024-01-22 10:30",
      content:
        "[INTRO]\nHook: Did you know that machine learning algorithms are behind 90% of the apps you use daily?\n[SEGMENT 1 - What is Machine Learning?]...",
    },
    {
      id: "7",
      title: "Facebook Ad Campaign: Holiday Season Sale - 5 Variations",
      type: "Ad Campaign",
      contentType: "advertisement",
      status: "Running",
      publishedTo: "Facebook Ads Manager",
      publishDate: "2024-01-20 00:00",
      scheduledDate: null,
      flowName: "Ad Campaign Generator",
      flowId: "12",
      adVariations: 5,
      budget: "$2,500",
      engagement: { impressions: 45230, clicks: 1205, conversions: 89 },
      author: "AI Assistant",
      humanReviewer: "Emma Davis",
      keywords: ["holiday sale", "e-commerce", "conversion"],
      platforms: ["Facebook", "Instagram"],
      lastModified: "2024-01-21 15:30",
      created: "2024-01-20 09:00",
      content:
        "🎄 Holiday Magic Awaits!\n\nDiscover gifts that spark joy this season. Up to 50% off selected items.\n\n[CTA: Shop Now]\n[Image: Holiday collection]",
    },
    {
      id: "8",
      title: "Product Description: Smart Home Security Camera X1",
      type: "Product Description",
      contentType: "ecommerce",
      status: "Published",
      publishedTo: "Shopify Store",
      publishDate: "2024-01-22 12:00",
      scheduledDate: null,
      flowName: "Product Description Generator",
      flowId: "4",
      wordCount: 247,
      conversionRate: "4.2%",
      author: "AI Assistant",
      humanReviewer: null,
      keywords: ["security camera", "smart home", "surveillance"],
      platforms: ["Shopify", "Amazon"],
      lastModified: "2024-01-22 11:50",
      created: "2024-01-22 11:45",
      content:
        "Transform your home security with the Smart Home Security Camera X1 - the ultimate guardian for modern living...",
    },
    {
      id: "9",
      title: "LinkedIn Article: The Rise of No-Code Development Platforms",
      type: "LinkedIn Article",
      contentType: "article",
      status: "Pending Review",
      publishedTo: null,
      publishDate: null,
      scheduledDate: null,
      flowName: "Professional Content Creator",
      flowId: "11",
      wordCount: 1156,
      author: "AI Assistant",
      humanReviewer: "Lisa Wong",
      keywords: ["no-code", "development", "digital transformation"],
      platforms: ["LinkedIn"],
      lastModified: "2024-01-22 17:20",
      created: "2024-01-22 16:45",
      content:
        "The democratization of software development is here, and it's changing everything we know about building digital solutions...",
    },
    {
      id: "10",
      title: "Instagram Story Series: Behind the Scenes - Startup Life",
      type: "Instagram Stories",
      contentType: "stories",
      status: "Expired",
      publishedTo: "Instagram",
      publishDate: "2024-01-21 09:00",
      scheduledDate: null,
      flowName: "Social Media Content Pipeline",
      flowId: "2",
      storyCount: 8,
      engagement: { views: 3420, replies: 45, shares: 67 },
      author: "AI Assistant",
      humanReviewer: "Zoe Martinez",
      keywords: ["startup", "behind the scenes", "company culture"],
      platforms: ["Instagram"],
      lastModified: "2024-01-21 08:55",
      created: "2024-01-21 08:30",
      content:
        "Story 1: ☕ 6 AM - The early bird catches the product launch\nStory 2: 💡 Brainstorming session with the team...",
    },
    {
      id: "11",
      title: "Press Release: TechCorp Announces Revolutionary AI Platform",
      type: "Press Release",
      contentType: "press",
      status: "Published",
      publishedTo: "PRNewswire",
      publishDate: "2024-01-22 10:00",
      scheduledDate: null,
      flowName: "Press Release Automation",
      flowId: "6",
      wordCount: 584,
      distribution: "National",
      author: "AI Assistant",
      humanReviewer: "Marcus Johnson",
      keywords: ["press release", "AI platform", "innovation"],
      platforms: ["PRNewswire", "Business Wire"],
      lastModified: "2024-01-22 09:45",
      created: "2024-01-22 09:20",
      content:
        "FOR IMMEDIATE RELEASE\n\nTechCorp Unveils Game-Changing AI Platform Set to Transform Enterprise Operations...",
    },
    {
      id: "12",
      title: "Email Sequence: Welcome Series for New Subscribers - Part 3/5",
      type: "Email Campaign",
      contentType: "email",
      status: "Scheduled",
      publishedTo: null,
      publishDate: null,
      scheduledDate: "2024-01-23 11:30",
      flowName: "Email Marketing Campaigns",
      flowId: "7",
      wordCount: 412,
      sequenceStep: "3/5",
      author: "AI Assistant",
      humanReviewer: null,
      keywords: ["welcome series", "onboarding", "customer engagement"],
      platforms: ["ConvertKit"],
      lastModified: "2024-01-22 15:15",
      created: "2024-01-22 15:00",
      content:
        "Subject: Here's what our top customers do differently\n\nHi [First Name],\n\nYou've been with us for a few days now, and I wanted to share something interesting...",
    },
    {
      id: "13",
      title: "TikTok Script: 30-Second Productivity Hack - Pomodoro Technique",
      type: "TikTok Video",
      contentType: "video",
      status: "Failed",
      publishedTo: null,
      publishDate: null,
      scheduledDate: null,
      flowName: "Short-form Video Creator",
      flowId: "14",
      duration: "30 seconds",
      author: "AI Assistant",
      humanReviewer: "Amanda Foster",
      keywords: ["productivity", "pomodoro", "life hacks"],
      platforms: ["TikTok", "Instagram Reels"],
      lastModified: "2024-01-22 12:30",
      created: "2024-01-22 12:15",
      content:
        "[Scene 1 - 0-3s]: Quick hook - 'This 25-minute trick changed my productivity forever'\n[Scene 2 - 4-10s]: Show timer setup...",
      failureReason: "Content policy violation - promotional content",
    },
    {
      id: "14",
      title: "Podcast Show Notes: Episode 47 - The Future of Remote Work",
      type: "Podcast Notes",
      contentType: "notes",
      status: "Published",
      publishedTo: "Podcast Website",
      publishDate: "2024-01-21 20:00",
      scheduledDate: null,
      flowName: "Podcast Show Notes Generator",
      flowId: "10",
      wordCount: 756,
      episodeDuration: "42:18",
      author: "AI Assistant",
      humanReviewer: null,
      keywords: ["remote work", "future of work", "productivity"],
      platforms: ["Podcast Website", "Spotify"],
      lastModified: "2024-01-21 19:55",
      created: "2024-01-21 19:30",
      content:
        "🎧 Episode 47: The Future of Remote Work\n\nIn this episode, we dive deep into the evolving landscape of remote work...",
    },
    {
      id: "15",
      title: "Customer Success Story: How AutoTech Increased ROI by 340%",
      type: "Case Study",
      contentType: "case_study",
      status: "Approved",
      publishedTo: null,
      publishDate: null,
      scheduledDate: "2024-01-24 15:00",
      flowName: "Social Proof Content Creator",
      flowId: "12",
      wordCount: 1247,
      author: "AI Assistant",
      humanReviewer: "Robert Kim",
      keywords: ["case study", "ROI", "customer success"],
      platforms: ["Company Website", "LinkedIn"],
      lastModified: "2024-01-22 16:40",
      created: "2024-01-22 16:10",
      content:
        "Challenge: AutoTech was struggling with manual processes that were eating into their profit margins...",
    },
  ];

  const columns = [
    { key: "title", header: "Title", width: "300px" },
    { key: "type", header: "Content Type", width: "140px" },
    { key: "status", header: "Status", width: "120px" },
    { key: "flowName", header: "Generated By", width: "180px" },
    { key: "publishedTo", header: "Published To", width: "150px" },
    { key: "humanReviewer", header: "Reviewer", width: "130px" },
    { key: "created", header: "Created", width: "120px" },
  ];

  const emptyActions = [
    {
      label: "Create Flow",
      icon: <Plus className="h-4 w-4" />,
      href: "/flows/create",
    },
  ];

  const tableActions = (
    <Button asChild>
      <Link href="/flows/create">
        <Plus className="h-4 w-4 mr-2" />
        Generate Content (via Flow)
      </Link>
    </Button>
  );

  // Row click handler
  const handleRowClick = (row: Record<string, any>) => {
    console.log("Viewing content:", row.title);
    // In a real app, you'd navigate to `/content/${row.id}`
  };

  // Custom row actions specific to content
  const rowActions = [
    {
      label: "View Content",
      icon: <Eye className="h-4 w-4" />,
      onClick: (row: Record<string, any>) =>
        console.log("View content:", row.title),
    },
    {
      label: "Edit Content",
      icon: <Edit2 className="h-4 w-4" />,
      onClick: (row: Record<string, any>) =>
        console.log("Edit content:", row.title),
    },
    {
      label: "Duplicate Content",
      icon: <Copy className="h-4 w-4" />,
      onClick: (row: Record<string, any>) =>
        console.log("Duplicate content:", row.title),
    },
    {
      label: "Schedule/Publish",
      icon: <Calendar className="h-4 w-4" />,
      onClick: (row: Record<string, any>) =>
        console.log("Schedule content:", row.title),
    },
    {
      label: "Share Content",
      icon: <Share2 className="h-4 w-4" />,
      onClick: (row: Record<string, any>) =>
        console.log("Share content:", row.title),
    },
    {
      label: "View Analytics",
      icon: <ExternalLink className="h-4 w-4" />,
      onClick: (row: Record<string, any>) =>
        console.log("View analytics:", row.title),
    },
    {
      label: "Delete Content",
      icon: <Trash2 className="h-4 w-4" />,
      onClick: (row: Record<string, any>) =>
        console.log("Delete content:", row.title),
      variant: "destructive" as const,
    },
  ];

  return (
    <PageLayout
      title="Content"
      description="View and manage all content generated through your automated flows and processes."
      breadcrumbs={breadcrumbs}
    >
      <DataTable
        columns={columns}
        data={contentData}
        emptyTitle="No content available"
        emptyDescription="Content will be automatically generated and managed through your configured flows."
        emptyActions={emptyActions}
        emptyIcon={<FileText className="h-8 w-8 text-muted-foreground" />}
        searchPlaceholder="Search content by title, type, status, platform..."
        actions={tableActions}
        onRowClick={handleRowClick}
        rowActions={rowActions}
        pageSize={12}
        searchFields={[
          "title",
          "type",
          "status",
          "flowName",
          "publishedTo",
          "humanReviewer",
        ]}
      />
    </PageLayout>
  );
}
