"use client";

import { CheckCircle, Clock, Sparkles, UserCheck } from "lucide-react";
import { useMemo } from "react";
import { dateFormat } from "@/lib/formatters/date-formatters";
import type { MetadataItem } from "@/types/detail-page";
import type { GeneratedTopic } from "@/types/topic-builder";

/**
 * Hook for building topic metadata items for display
 *
 * @param topic - Generated topic object
 * @returns Array of metadata items
 */
export function useTopicMetadata(
  topic: GeneratedTopic | null | undefined,
): MetadataItem[] {
  return useMemo(() => {
    if (!topic) return [];

    const items: MetadataItem[] = [
      {
        label: "Generated By",
        value: "Mobeen Abdullah",
        icon: <UserCheck className="h-4 w-4" />,
      },
      {
        label: "Generated On",
        value: topic.created_at
          ? dateFormat.shortWithTime(topic.created_at)
          : "Not available",
        icon: <Sparkles className="h-4 w-4" />,
      },
      {
        label: "Last Updated",
        value:
          topic.updated_at && topic.updated_at !== topic.created_at
            ? dateFormat.shortWithTime(topic.updated_at)
            : "No updates",
        icon: <Clock className="h-4 w-4" />,
      },
    ];

    // Add approved date if available
    if (topic.approved_at) {
      items.push({
        label: "Approved On",
        value: dateFormat.shortWithTime(topic.approved_at),
        icon: <CheckCircle className="h-4 w-4" />,
      });
    }

    return items;
  }, [topic]);
}
