"use client";

import {
  AlertTriangle,
  BarChart3,
  Building,
  CheckCircle,
  Clock,
  Crosshair,
  Eye,
  FileText,
  Flame,
  Gem,
  Globe,
  Hash,
  PenTool,
  Save,
  Sparkles,
  Target,
  Trash2,
  TrendingUp,
  UserCheck,
  Users,
  Wrench,
  Zap,
} from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { DetailPageWrapper } from "@/components/detail-page-wrapper";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DetailCard } from "@/components/ui/detail-card";
import { DetailGrid, DetailGridItem } from "@/components/ui/detail-grid";
import { SectionHeader } from "@/components/ui/section-header";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { usePageTitle } from "@/hooks/use-page-title";
import { useTopicApproveServerAction } from "@/hooks/use-topic-mutations-server-actions";
import { useTopicDeleteMutation } from "@/hooks/useTopicMutations";
import { logger } from "@/lib/logger";
import { useCurrentWorkspace } from "@/stores/workspace-store";
import type { MetadataItem, SidebarConfig } from "@/types/detail-page";
import type { GeneratedTopic } from "@/types/topic-builder";

interface TopicDetailClientProps {
  topic: GeneratedTopic;
}

export function TopicDetailClient({ topic }: TopicDetailClientProps) {
  const router = useRouter();
  const [isDeleting, setIsDeleting] = useState(false);
  const detailLogger = logger.forComponent("TopicDetailClient");
  const currentWorkspace = useCurrentWorkspace();
  const workspaceId = currentWorkspace?.id || "";

  const deleteMutation = useTopicDeleteMutation(workspaceId);
  const approveMutation = useTopicApproveServerAction();

  // The topic data is already in the correct GeneratedTopic format
  const generatedTopic = topic;

  // Update page title and description dynamically
  usePageTitle(
    generatedTopic?.title || "Topic Detail",
    generatedTopic?.description ||
      generatedTopic?.angle ||
      `Topic details and analytics for ${generatedTopic?.title || "selected topic"}`,
  );

  // Calculate overall score using same weighted formula as topics table
  const calculateOverallScore = (scores: GeneratedTopic["scores"]): number => {
    if (!scores) return 0;
    const {
      relevance = 0,
      seo_potential = 0,
      trend_level = 0,
      uniqueness = 0,
      reader_interest = 0,
      actionable_potential = 0,
      brand_alignment = 0,
      controversy = 0,
    } = scores;

    // Weighted average of all score components (same as simple-topic-transformer.ts)
    // Note: controversy is inverted (lower controversy = higher score)
    const totalScore =
      relevance * 0.2 +
      seo_potential * 0.15 +
      trend_level * 0.15 +
      uniqueness * 0.1 +
      reader_interest * 0.15 +
      actionable_potential * 0.1 +
      brand_alignment * 0.1 +
      (1 - controversy) * 0.05;

    return Math.round(totalScore * 100);
  };

  const overallScore = generatedTopic
    ? calculateOverallScore(generatedTopic.scores)
    : 0;

  // Handle topic actions
  const handleApproveTopic = async () => {
    if (!generatedTopic) return;
    try {
      await approveMutation.mutateAsync(generatedTopic.id);
      detailLogger.info("Topic approved successfully", {
        topic_id: generatedTopic.id,
        title: generatedTopic.title,
      });
    } catch (error) {
      detailLogger.error("Failed to approve topic", {
        topic_id: generatedTopic.id,
        error: error instanceof Error ? error.message : String(error),
      });
    }
  };

  const handleUseTopic = () => {
    detailLogger.info("Topic selected for content creation", {
      topic_id: generatedTopic?.id,
      title: generatedTopic?.title,
    });
    // TODO: Navigate to content creation with topic prefilled
  };

  const handleDeleteTopic = async () => {
    if (!generatedTopic) return;
    setIsDeleting(true);
    try {
      await deleteMutation.mutateAsync([generatedTopic.id]);
      router.push("/topics");
    } catch (error) {
      detailLogger.error("Failed to delete topic", {
        topic_id: generatedTopic.id,
        error: error instanceof Error ? error.message : String(error),
      });
    } finally {
      setIsDeleting(false);
    }
  };

  // Build breadcrumbs
  const breadcrumbs = [
    { label: "Library", href: "#" },
    { label: "Topics", href: "/topics" },
    { label: generatedTopic?.title || "Topic Detail" },
  ];

  // Build metadata for the wrapper using GeneratedTopic structure
  const metadata: MetadataItem[] = generatedTopic
    ? [
        {
          label: "Generated By",
          value: "Mobeen Abdullah",
          icon: <UserCheck className="h-4 w-4" />,
        },
        {
          label: "Generated On",
          value: generatedTopic.created_at
            ? new Date(generatedTopic.created_at).toLocaleDateString("en-US", {
                month: "short",
                day: "numeric",
                year: "numeric",
                hour: "numeric",
                minute: "2-digit",
                hour12: true,
              })
            : "Not available",
          icon: <Sparkles className="h-4 w-4" />,
        },
        {
          label: "Last Updated",
          value:
            generatedTopic.updated_at &&
            generatedTopic.updated_at !== generatedTopic.created_at
              ? new Date(generatedTopic.updated_at).toLocaleDateString(
                  "en-US",
                  {
                    month: "short",
                    day: "numeric",
                    year: "numeric",
                    hour: "numeric",
                    minute: "2-digit",
                    hour12: true,
                  },
                )
              : "No updates",
          icon: <Clock className="h-4 w-4" />,
        },
        ...(generatedTopic.approved_at
          ? [
              {
                label: "Approved On",
                value: new Date(generatedTopic.approved_at).toLocaleDateString(
                  "en-US",
                  {
                    month: "short",
                    day: "numeric",
                    year: "numeric",
                    hour: "numeric",
                    minute: "2-digit",
                    hour12: true,
                  },
                ),
                icon: <CheckCircle className="h-4 w-4" />,
              },
            ]
          : []),
      ]
    : [];

  // Build header actions for page header
  const headerActions = (
    <div className="flex items-center gap-2">
      {/* Approve - First and primary when not approved */}
      {!generatedTopic?.approved && (
        <Tooltip>
          <TooltipTrigger asChild>
            <Button
              onClick={handleApproveTopic}
              disabled={approveMutation.isPending}
              className="gap-2"
            >
              {approveMutation.isPending ? (
                <div className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
              ) : (
                <Save className="h-4 w-4" />
              )}
              Approve Topic
            </Button>
          </TooltipTrigger>
          <TooltipContent>Approve topic for content creation</TooltipContent>
        </Tooltip>
      )}

      {/* Write Content - Only show when approved */}
      {generatedTopic?.approved && (
        <Tooltip>
          <TooltipTrigger asChild>
            <Button onClick={handleUseTopic} className="gap-2">
              <PenTool className="h-4 w-4" />
              Write Content
            </Button>
          </TooltipTrigger>
          <TooltipContent>Use this topic to create new content</TooltipContent>
        </Tooltip>
      )}

      {/* Remove Topic */}
      <Tooltip>
        <TooltipTrigger asChild>
          <Button
            onClick={handleDeleteTopic}
            disabled={isDeleting || deleteMutation.isPending}
            variant="destructive"
            className="gap-2"
          >
            {isDeleting ? (
              <div className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
            ) : (
              <Trash2 className="h-4 w-4" />
            )}
            Remove
          </Button>
        </TooltipTrigger>
        <TooltipContent>Remove this topic permanently</TooltipContent>
      </Tooltip>
    </div>
  );

  // Build new flexible sidebar configuration with revamped overall score card
  const sidebarConfig: SidebarConfig = {
    cards: [
      // Overall Score Card - Using standard DetailCard
      {
        type: "custom",
        config: {
          id: "overall-score-card",
          content: (
            <DetailCard variant="default" className="relative">
              <div className="flex items-start justify-between mb-4">
                <SectionHeader
                  title="Overall Quality Score"
                  icon={<TrendingUp className="w-5 h-5" />}
                  variant="spacious"
                  className="mb-0"
                />
                <div
                  className={`px-2 py-1 rounded-full text-xs font-medium ${
                    overallScore >= 80
                      ? "bg-green-100 text-green-700 dark:bg-green-950/50 dark:text-green-400"
                      : overallScore >= 60
                        ? "bg-blue-100 text-blue-700 dark:bg-blue-950/50 dark:text-blue-400"
                        : overallScore >= 40
                          ? "bg-yellow-100 text-yellow-700 dark:bg-yellow-950/50 dark:text-yellow-400"
                          : "bg-red-100 text-red-700 dark:bg-red-950/50 dark:text-red-400"
                  }`}
                >
                  {overallScore >= 80
                    ? "Excellent"
                    : overallScore >= 60
                      ? "Good"
                      : overallScore >= 40
                        ? "Fair"
                        : "Needs Work"}
                </div>
              </div>

              {/* Main Score Display - Dashboard Style */}
              <div className="text-center mb-6">
                <div className="relative inline-flex items-center justify-center mb-2">
                  {/* Dashboard Segments - Perfect Rounded Arc */}
                  <svg
                    className="w-48 h-32"
                    viewBox="0 0 192 128"
                    aria-label="Quality score dashboard indicator"
                  >
                    <title>Quality Score Dashboard</title>
                    {/* Background Arc - Perfect Semicircle */}
                    <path
                      d="M 24 104 A 72 72 0 0 1 168 104"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="12"
                      strokeLinecap="round"
                      className="text-muted/20"
                    />

                    {/* Colored Segments using multiple overlaid arcs */}
                    {/* Red Zone (0-25) */}
                    <path
                      d="M 24 104 A 72 72 0 0 1 168 104"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="12"
                      strokeLinecap="round"
                      strokeDasharray={`${226.19 * 0.25} ${226.19 * 0.75}`}
                      strokeDashoffset="0"
                      className={`transition-all duration-1000 ease-out ${
                        overallScore >= 0 && overallScore < 25
                          ? "text-red-500"
                          : overallScore >= 25
                            ? "text-red-300/40"
                            : "text-red-200/20"
                      }`}
                    />

                    {/* Yellow Zone (25-50) */}
                    <path
                      d="M 24 104 A 72 72 0 0 1 168 104"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="12"
                      strokeLinecap="round"
                      strokeDasharray={`${226.19 * 0.25} ${226.19 * 0.75}`}
                      strokeDashoffset={`-${226.19 * 0.25}`}
                      className={`transition-all duration-1000 ease-out ${
                        overallScore >= 25 && overallScore < 50
                          ? "text-yellow-500"
                          : overallScore >= 50
                            ? "text-yellow-300/40"
                            : "text-yellow-200/20"
                      }`}
                    />

                    {/* Blue Zone (50-75) */}
                    <path
                      d="M 24 104 A 72 72 0 0 1 168 104"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="12"
                      strokeLinecap="round"
                      strokeDasharray={`${226.19 * 0.25} ${226.19 * 0.75}`}
                      strokeDashoffset={`-${226.19 * 0.5}`}
                      className={`transition-all duration-1000 ease-out ${
                        overallScore >= 50 && overallScore < 75
                          ? "text-blue-500"
                          : overallScore >= 75
                            ? "text-blue-300/40"
                            : "text-blue-200/20"
                      }`}
                    />

                    {/* Green Zone (75-100) */}
                    <path
                      d="M 24 104 A 72 72 0 0 1 168 104"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="12"
                      strokeLinecap="round"
                      strokeDasharray={`${226.19 * 0.25} ${226.19 * 0.75}`}
                      strokeDashoffset={`-${226.19 * 0.75}`}
                      className={`transition-all duration-1000 ease-out ${
                        overallScore >= 75
                          ? "text-green-500"
                          : "text-green-200/20"
                      }`}
                    />

                    {/* Score Indicator Needle with Gap */}
                    <g
                      className="transition-transform duration-1000 ease-out"
                      style={{
                        transformOrigin: "96px 104px",
                        transform: `rotate(${-90 + (overallScore / 100) * 180}deg)`,
                      }}
                    >
                      {/* Needle starts with gap from center and doesn't touch the arc */}
                      <line
                        x1="96"
                        y1="88"
                        x2="96"
                        y2="50"
                        stroke="currentColor"
                        strokeWidth="4"
                        strokeLinecap="round"
                        className="text-foreground drop-shadow-lg"
                      />
                      <circle
                        cx="96"
                        cy="104"
                        r="7"
                        fill="currentColor"
                        className="text-foreground"
                      />
                      {/* Inner circle for better visual */}
                      <circle
                        cx="96"
                        cy="104"
                        r="3"
                        fill="currentColor"
                        className="text-background"
                      />
                    </g>
                  </svg>
                </div>

                {/* Score Display Below Dashboard */}
                <div className="text-center">
                  <div className="text-4xl font-bold text-foreground leading-none mb-1">
                    {overallScore}
                  </div>
                  <div className="text-sm font-medium text-muted-foreground">
                    out of 100 points
                  </div>
                </div>
              </div>

              {/* Complete Score Breakdown */}
              <div className="space-y-3">
                <div className="text-xs font-medium text-muted-foreground">
                  Performance Breakdown:
                </div>
                <div className="space-y-3">
                  {[
                    {
                      label: "Relevance",
                      value: Math.round(
                        (generatedTopic?.scores.relevance || 0) * 100,
                      ),
                      weight: "20%",
                      tooltip:
                        "How well the topic matches your specified criteria and goals",
                      icon: <Crosshair className="w-3.5 h-3.5" />,
                    },
                    {
                      label: "SEO Potential",
                      value: Math.round(
                        (generatedTopic?.scores.seo_potential || 0) * 100,
                      ),
                      weight: "15%",
                      tooltip:
                        "Likelihood to rank well in search engines and attract organic traffic",
                      icon: <BarChart3 className="w-3.5 h-3.5" />,
                    },
                    {
                      label: "Reader Interest",
                      value: Math.round(
                        (generatedTopic?.scores.reader_interest || 0) * 100,
                      ),
                      weight: "15%",
                      tooltip:
                        "Expected audience engagement and appeal to your target readers",
                      icon: <Eye className="w-3.5 h-3.5" />,
                    },
                    {
                      label: "Trend Level",
                      value: Math.round(
                        (generatedTopic?.scores.trend_level || 0) * 100,
                      ),
                      weight: "15%",
                      tooltip:
                        "How current and trending the topic is in your industry",
                      icon: <Flame className="w-3.5 h-3.5" />,
                    },
                    {
                      label: "Uniqueness",
                      value: Math.round(
                        (generatedTopic?.scores.uniqueness || 0) * 100,
                      ),
                      weight: "10%",
                      tooltip:
                        "Originality of the angle and approach compared to existing content",
                      icon: <Gem className="w-3.5 h-3.5" />,
                    },
                    {
                      label: "Actionable",
                      value: Math.round(
                        (generatedTopic?.scores.actionable_potential || 0) *
                          100,
                      ),
                      weight: "10%",
                      tooltip:
                        "How practical and implementable the content advice will be",
                      icon: <Wrench className="w-3.5 h-3.5" />,
                    },
                    {
                      label: "Brand Alignment",
                      value: Math.round(
                        (generatedTopic?.scores.brand_alignment || 0) * 100,
                      ),
                      weight: "10%",
                      tooltip:
                        "How well the topic fits with your brand values and messaging",
                      icon: <Building className="w-3.5 h-3.5" />,
                    },
                    {
                      label: "Controversy",
                      value: Math.round(
                        (generatedTopic?.scores.controversy || 0) * 100,
                      ),
                      weight: "5%",
                      tooltip:
                        "Potential for polarizing opinions (lower is safer for most brands)",
                      icon: <AlertTriangle className="w-3.5 h-3.5" />,
                    },
                  ]
                    .sort((a, b) => b.value - a.value)
                    .map((score) => (
                      <Tooltip key={score.label}>
                        <TooltipTrigger asChild>
                          <div className="flex items-center justify-between py-1 cursor-help hover:bg-muted/10 rounded-md px-1 transition-colors">
                            <div className="flex items-center gap-3">
                              <div
                                className={`p-1.5 rounded-md shadow-sm ${
                                  score.value >= 80
                                    ? "bg-green-100 text-green-600 dark:bg-green-950/50 dark:text-green-400"
                                    : score.value >= 60
                                      ? "bg-blue-100 text-blue-600 dark:bg-blue-950/50 dark:text-blue-400"
                                      : score.value >= 40
                                        ? "bg-yellow-100 text-yellow-600 dark:bg-yellow-950/50 dark:text-yellow-400"
                                        : "bg-red-100 text-red-600 dark:bg-red-950/50 dark:text-red-400"
                                }`}
                              >
                                {score.icon}
                              </div>
                              <span className="text-sm font-medium text-foreground">
                                {score.label}
                              </span>
                            </div>
                            <div className="flex items-center gap-3">
                              <div className="w-12 bg-muted/100 rounded-full h-1.5 overflow-hidden">
                                <div
                                  className={`h-full rounded-full transition-all duration-500 ease-out ${
                                    score.value >= 80
                                      ? "bg-green-500"
                                      : score.value >= 60
                                        ? "bg-blue-500"
                                        : score.value >= 40
                                          ? "bg-yellow-500"
                                          : "bg-red-500"
                                  }`}
                                  style={{ width: `${score.value}%` }}
                                />
                              </div>
                              <span className="text-sm font-semibold text-foreground min-w-[2rem] text-right">
                                {score.value}%
                              </span>
                            </div>
                          </div>
                        </TooltipTrigger>
                        <TooltipContent side="left" className="max-w-[280px]">
                          <div className="space-y-1">
                            <div className="font-medium">{score.label}</div>
                            <div className="text-xs text-muted-foreground mb-1">
                              {score.tooltip}
                            </div>
                            <div className="text-xs text-primary font-medium">
                              Weight: {score.weight} of overall score
                            </div>
                          </div>
                        </TooltipContent>
                      </Tooltip>
                    ))}
                </div>
              </div>

              {/* Explanatory Note */}
              <div className="mt-4 pt-3 border-t border-muted/20">
                <p className="text-[10px] text-muted-foreground leading-relaxed">
                  💡 These scores are based on your selections and preferences
                  from when this topic was originally generated in the Topic
                  Builder wizard.
                </p>
              </div>
            </DetailCard>
          ),
        },
      },
    ],
    order: ["cards", "quickActions"], // Custom order - removed metadata
  };

  return (
    <DetailPageWrapper
      title={generatedTopic?.title || "Topic Detail"}
      breadcrumbs={breadcrumbs}
      status={generatedTopic?.approved ? "Approved" : "Pending Approval"}
      statusVariant={generatedTopic?.approved ? "default" : "outline"}
      metadata={[]}
      headerActions={headerActions}
      sidebarConfig={sidebarConfig}
      isLoading={false}
      error={undefined}
    >
      {/* Main Content - Enhanced Visual Layout */}
      <div className="space-y-8">
        {/* Topic Details Info Boxes */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {metadata.map((item) => (
            <div
              key={item.label}
              className="bg-gradient-to-br from-muted/5 to-muted/10 border border-muted/20 rounded-lg p-4 hover:border-muted/30 transition-all duration-200"
            >
              <div className="flex items-start gap-3">
                {/* Icon Column */}
                <div className="p-2 rounded-md bg-primary/10 text-primary flex-shrink-0">
                  {item.icon}
                </div>
                {/* Key/Value Column */}
                <div className="flex-1 min-w-0">
                  <div className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-1">
                    {item.label}
                  </div>
                  <div className="text-sm font-semibold text-foreground leading-tight">
                    {item.value}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Topic Information */}
        <DetailCard
          variant="highlight"
          className="bg-muted/20 dark:bg-muted/10"
        >
          <SectionHeader
            title="Topic Information"
            icon={<FileText className="w-5 h-5" />}
            variant="spacious"
            className="mb-6"
          />

          <div className="space-y-6">
            {/* Overview - Most Prominent */}
            <div className="bg-background rounded-lg p-6 border-2 border-muted/40 shadow-sm">
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center mt-1">
                  <FileText className="w-5 h-5 text-primary" />
                </div>
                <div className="flex-1">
                  <h3 className="text-lg font-medium text-foreground mb-3">
                    Overview
                  </h3>
                  <p className="text-base leading-relaxed text-muted-foreground">
                    {generatedTopic?.description ||
                      "No description available for this topic."}
                  </p>
                </div>
              </div>
            </div>

            {/* Secondary Info Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Angle */}
              {generatedTopic?.angle && (
                <div className="bg-background rounded-lg p-5 border-2 border-muted/50 shadow-sm">
                  <div className="flex items-start gap-3">
                    <div className="flex-shrink-0 w-8 h-8 bg-primary/10 rounded-lg flex items-center justify-center mt-0.5">
                      <Sparkles className="w-4 h-4 text-primary" />
                    </div>
                    <div className="flex-1">
                      <h4 className="text-base font-medium text-foreground mb-2">
                        Angle
                      </h4>
                      <p className="text-sm leading-relaxed text-muted-foreground">
                        {generatedTopic.angle}
                      </p>
                    </div>
                  </div>
                </div>
              )}

              {/* Why This Works */}
              {generatedTopic?.why_it_works && (
                <div className="bg-background rounded-lg p-5 border-2 border-muted/50 shadow-sm">
                  <div className="flex items-start gap-3">
                    <div className="flex-shrink-0 w-8 h-8 bg-primary/10 rounded-lg flex items-center justify-center mt-0.5">
                      <Target className="w-4 h-4 text-primary" />
                    </div>
                    <div className="flex-1">
                      <h4 className="text-base font-medium text-foreground mb-2">
                        Why This Works
                      </h4>
                      <p className="text-sm leading-relaxed text-muted-foreground">
                        {generatedTopic.why_it_works}
                      </p>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>
        </DetailCard>

        {/* Keywords & Channel/Audience Fit - Strategic Bottom Section */}
        {((generatedTopic?.tags?.length ?? 0) > 0 ||
          (generatedTopic?.channel_fit?.length ?? 0) > 0 ||
          (generatedTopic?.audience_fit?.length ?? 0) > 0) && (
          <DetailGrid columns={3} gap="lg" responsive={{ sm: 1, md: 2, lg: 3 }}>
            {/* Keywords & Tags - Takes 1 column */}
            <DetailGridItem span={1} className="flex">
              {generatedTopic?.tags && generatedTopic.tags.length > 0 ? (
                <DetailCard
                  variant="accent"
                  gradient
                  className="flex-1 flex flex-col"
                >
                  <SectionHeader
                    title="Keywords & Tags"
                    icon={<Hash className="w-5 h-5" />}
                    variant="compact"
                    className="mb-4"
                  />
                  <div className="flex-1">
                    <div className="flex flex-wrap gap-2">
                      {generatedTopic.tags
                        .slice(0, 6)
                        .map((keyword: string) => (
                          <Badge
                            key={keyword}
                            variant="secondary"
                            className="text-sm px-4 py-2 bg-gradient-to-r from-white/90 to-purple-50/90 dark:from-background/90 dark:to-purple-900/20 border border-purple-200/60 dark:border-purple-700/60 hover:border-purple-300/80 dark:hover:border-purple-600/80 hover:shadow-sm transition-all duration-200 font-medium"
                          >
                            <Hash className="w-3 h-3 mr-1.5 text-purple-500" />
                            {keyword}
                          </Badge>
                        ))}
                      {generatedTopic.tags.length > 6 && (
                        <Badge variant="outline" className="text-sm">
                          +{generatedTopic.tags.length - 6} more
                        </Badge>
                      )}
                    </div>
                  </div>
                </DetailCard>
              ) : (
                <DetailCard variant="default" className="flex-1 flex flex-col">
                  <SectionHeader
                    title="Keywords & Tags"
                    icon={<Hash className="w-5 h-5" />}
                    variant="compact"
                    className="mb-4"
                  />
                  <div className="flex-1 flex items-start">
                    <p className="text-sm text-muted-foreground">
                      No keywords available.
                    </p>
                  </div>
                </DetailCard>
              )}
            </DetailGridItem>

            {/* Channel Fit - Takes 1 column */}
            <DetailGridItem span={1} className="flex">
              {(generatedTopic?.channel_fit?.length ?? 0) > 0 ? (
                <DetailCard
                  variant="info"
                  gradient
                  className="flex-1 flex flex-col"
                >
                  <SectionHeader
                    title="Best Channels"
                    icon={<Globe className="w-5 h-5" />}
                    variant="compact"
                    className="mb-4"
                  />
                  <div className="flex-1">
                    <div className="flex flex-wrap gap-2">
                      {generatedTopic?.channel_fit
                        ?.slice(0, 4)
                        .map((channel: string) => (
                          <Badge
                            key={channel}
                            variant="secondary"
                            className="text-sm px-4 py-2 bg-gradient-to-r from-blue-50/90 to-sky-50/90 dark:from-blue-950/30 dark:to-sky-950/30 border border-blue-200/60 dark:border-blue-700/60 hover:border-blue-300/80 dark:hover:border-blue-600/80 hover:shadow-sm transition-all duration-200 font-medium"
                          >
                            <Zap className="w-3 h-3 mr-1.5 text-blue-600 dark:text-blue-400" />
                            {channel}
                          </Badge>
                        ))}
                      {(generatedTopic?.channel_fit?.length ?? 0) > 4 && (
                        <Badge variant="outline" className="text-sm">
                          +{(generatedTopic?.channel_fit?.length ?? 0) - 4} more
                        </Badge>
                      )}
                    </div>
                  </div>
                </DetailCard>
              ) : (
                <DetailCard variant="default" className="flex-1 flex flex-col">
                  <SectionHeader
                    title="Best Channels"
                    icon={<Globe className="w-5 h-5" />}
                    variant="compact"
                    className="mb-4"
                  />
                  <div className="flex-1 flex items-start">
                    <p className="text-sm text-muted-foreground">
                      No channel data available.
                    </p>
                  </div>
                </DetailCard>
              )}
            </DetailGridItem>

            {/* Audience Fit - Takes 1 column */}
            <DetailGridItem span={1} className="flex">
              {(generatedTopic?.audience_fit?.length ?? 0) > 0 ? (
                <DetailCard variant="default" className="flex-1 flex flex-col">
                  <SectionHeader
                    title="Target Audience"
                    icon={<Users className="w-5 h-5" />}
                    variant="compact"
                    className="mb-4"
                  />
                  <div className="flex-1">
                    <div className="flex flex-wrap gap-2">
                      {generatedTopic?.audience_fit
                        ?.slice(0, 4)
                        .map((audience: string) => (
                          <Badge
                            key={audience}
                            variant="secondary"
                            className="text-sm px-4 py-2 bg-gradient-to-r from-emerald-50/90 to-green-50/90 dark:from-emerald-950/30 dark:to-green-950/30 border border-emerald-200/60 dark:border-emerald-700/60 hover:border-emerald-300/80 dark:hover:border-emerald-600/80 hover:shadow-sm transition-all duration-200 font-medium"
                          >
                            <Target className="w-3 h-3 mr-1.5 text-emerald-600 dark:text-emerald-400" />
                            {audience}
                          </Badge>
                        ))}
                      {(generatedTopic?.audience_fit?.length ?? 0) > 4 && (
                        <Badge variant="outline" className="text-sm">
                          +{(generatedTopic?.audience_fit?.length ?? 0) - 4}{" "}
                          more
                        </Badge>
                      )}
                    </div>
                  </div>
                </DetailCard>
              ) : (
                <DetailCard variant="default" className="flex-1 flex flex-col">
                  <SectionHeader
                    title="Target Audience"
                    icon={<Users className="w-5 h-5" />}
                    variant="compact"
                    className="mb-4"
                  />
                  <div className="flex-1 flex items-start">
                    <p className="text-sm text-muted-foreground">
                      No audience data available.
                    </p>
                  </div>
                </DetailCard>
              )}
            </DetailGridItem>
          </DetailGrid>
        )}
      </div>
    </DetailPageWrapper>
  );
}
